/-
Copyright (c) 2026 Tom Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Diem
-/
module

public import Mathlib.Algebra.Lie.OfAssociative
public import Mathlib.Tactic.NoncommRing
public import Mathlib.LinearAlgebra.Matrix.StdBasis
public import Mathlib.Data.Matrix.Basis
public import Physlib.Mathematics.LieHomOfBasis
/-!

# Ladder systems

## i. Overview

A `LadderSystem K V d` packages `d` independent pairs of creation/annihilation endomorphisms of a
`K`-vector space `V` satisfying the canonical commutation relations -- the pure-algebra content
shared by *every* bosonic system (a literal quantum harmonic oscillator, a multi-mode Fock space
in QFT, squeezed light, ...), independent of any particular representation. The bilinears
`E i j := acᵢaⱼ` satisfy the `gl(d)` commutation relations, giving `V` a genuine `gl(d)`-module
structure via `toGlHom`, for free. Everything in `LadderSystem/` is proved from the three defining
relations alone: no analysis, no Hilbert space, nothing physics-specific.

- `Basic.lean` : this file -- the structure itself, the `gl(d)`-module structure it generates, and
    the number operator.
- `Vacuum.lean` : a vacuum state, the creation-operator words built over it, and the excitation-
    number sector they span, bundled as a `gl(d)` Lie submodule.
- `OccupationBasis.lean` : the occupation-number states form a genuine basis of each fixed-
    excitation-number sector, with an explicit dimension formula.
- `SymmetricPower.lean` : that sector is linearly isomorphic to `Sym^n(K^d)`.

A concrete physical system's own job is only to exhibit its operators as a `LadderSystem` instance
(see `QuantumMechanics/HarmonicOscillator/LadderOperators.lean`) and inherit everything here for
free.

## ii. Key results

Definitions:
- `LadderSystem.E` : the `gl(d)` bilinears `E i j := acᵢaⱼ`.
- `LadderSystem.toGlHom` : the `gl(d)`-representation on `V` generated by a ladder system.
- `LadderSystem.N` : the number operator for mode `i`, `Nᵢ ≔ Eᵢᵢ`.

Theorems:
- `LadderSystem.lie_E` : `E` satisfies the defining relations of `gl(d)`.
- `LadderSystem.lie_N_a`, `LadderSystem.lie_N_ac` : `[Nᵢ, aⱼ] = -δᵢⱼaᵢ` and
    `[Nᵢ, acⱼ] = δᵢⱼacᵢ`.
- `LadderSystem.lie_N_N` : the number operators commute among themselves, `[Nᵢ, Nⱼ] = 0`.

## iii. Table of contents

- A. The `LadderSystem` structure
- B. The `gl(d)`-module structure
- C. The number operator
  - C.1. Commutation relations

## iv. References

-/

@[expose] public section

open Module (Basis)

/-!

## A. The `LadderSystem` structure

-/

attribute [local instance 100] LieRing.ofAssociativeRing

/-- A system of `d` independent ladder pairs on a `K`-vector space `V`: annihilation operators
`a i` and creation operators `ac i` (`i : Fin d`), satisfying the canonical commutation relations.
A physical system exhibits its own concrete operators as one instance of this (e.g.
`QuantumMechanics/HarmonicOscillator/LadderOperators.lean`'s `toLadderSystem`, via
`ContinuousLinearMap.toLinearMap`) and inherits every result in `LadderSystem/` for free. -/
structure LadderSystem (K V : Type*) [Field K] [AddCommGroup V] [Module K V] (d : ℕ) where
  /-- The `d` annihilation operators. -/
  a : Fin d → Module.End K V
  /-- The `d` creation operators, `a⁺`. -/
  ac : Fin d → Module.End K V
  /-- `[a i, ac j] = δᵢⱼ`. -/
  comm_a_ac : ∀ i j, (⁅a i, ac j⁆ : Module.End K V) = if i = j then 1 else 0
  /-- `[a i, a j] = 0`. -/
  comm_a_a : ∀ i j, (⁅a i, a j⁆ : Module.End K V) = 0
  /-- `[ac i, ac j] = 0`. -/
  comm_ac_ac : ∀ i j, (⁅ac i, ac j⁆ : Module.End K V) = 0

namespace LadderSystem

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V] {d : ℕ} (L : LadderSystem K V d)

private theorem assoc_leibniz (x y z : Module.End K V) :
    (⁅x, y * z⁆ : Module.End K V) = ⁅x, y⁆ * z + y * ⁅x, z⁆ := by
  simp only [LieRing.of_associative_ring_bracket]
  noncomm_ring

private theorem assoc_leibniz' (x y z : Module.End K V) :
    (⁅x * y, z⁆ : Module.End K V) = x * ⁅y, z⁆ + ⁅x, z⁆ * y := by
  simp only [LieRing.of_associative_ring_bracket]
  noncomm_ring

/-!

## B. The `gl(d)`-module structure

-/

/-- The `gl(d)` bilinears `E i j := ac i · a j`. -/
def E (i j : Fin d) : Module.End K V := L.ac i * L.a j

/-- `E` satisfies the defining relations of `gl(d)`:
`[E i j, E k l] = δⱼₖ E i l - δₗᵢ E k j`. -/
theorem lie_E (i j k l : Fin d) :
    (⁅L.E i j, L.E k l⁆ : Module.End K V)
      = (if j = k then L.E i l else 0) - (if l = i then L.E k j else 0) := by
  show (⁅L.ac i * L.a j, L.ac k * L.a l⁆ : Module.End K V) = _
  rw [assoc_leibniz' (L.ac i) (L.a j) (L.ac k * L.a l), assoc_leibniz (L.a j) (L.ac k) (L.a l),
    assoc_leibniz (L.ac i) (L.ac k) (L.a l), L.comm_a_ac j k, L.comm_a_a j l, L.comm_ac_ac i k]
  have hAl : (⁅L.ac i, L.a l⁆ : Module.End K V) =
      -(if l = i then (1 : Module.End K V) else 0) := by
    rw [← lie_skew, L.comm_a_ac l i]
  rw [hAl]
  by_cases hjk : j = k <;> by_cases hli : l = i <;>
    simp [hjk, hli, E, mul_zero, zero_mul, mul_one, one_mul, sub_eq_add_neg]

/-- The matrix units satisfy the same relations, at the level of `gl(d)` itself. -/
theorem lie_single (i j k l : Fin d) :
    (⁅Matrix.single i j (1 : K), Matrix.single k l (1 : K)⁆ : Matrix (Fin d) (Fin d) K)
      = (if j = k then Matrix.single i l 1 else 0) -
        (if l = i then Matrix.single k j 1 else 0) := by
  rw [LieRing.of_associative_ring_bracket]
  by_cases hjk : j = k <;> by_cases hli : l = i <;>
    simp [Matrix.single_mul_single_same, Matrix.single_mul_single_of_ne, hjk, hli,
      sub_eq_add_neg]

/-- The `K`-linear map sending matrix unit `Matrix.single i j 1` to `E i j`. -/
noncomputable def toGlHomLinear (L : LadderSystem K V d) :
    Matrix (Fin d) (Fin d) K →ₗ[K] Module.End K V :=
  (Matrix.stdBasis K (Fin d) (Fin d)).constr K (fun p => L.E p.1 p.2)

@[simp] theorem toGlHomLinear_stdBasis (L : LadderSystem K V d) (i j : Fin d) :
    L.toGlHomLinear (Matrix.stdBasis K (Fin d) (Fin d) (i, j)) = L.E i j :=
  Basis.constr_basis _ _ _ _

theorem toGlHomLinear_single (L : LadderSystem K V d) (i j : Fin d) :
    L.toGlHomLinear (Matrix.single i j (1 : K)) = L.E i j := by
  rw [← Matrix.stdBasis_eq_single, toGlHomLinear_stdBasis]

/-- `toGlHomLinear` respects brackets. -/
theorem toGlHomLinear_lie (L : LadderSystem K V d) (x y : Matrix (Fin d) (Fin d) K) :
    L.toGlHomLinear ⁅x, y⁆ = ⁅L.toGlHomLinear x, L.toGlHomLinear y⁆ := by
  apply LinearMap.lie_apply_eq_of_lie_basis_eq (Matrix.stdBasis K (Fin d) (Fin d)) L.toGlHomLinear
  rintro ⟨i, j⟩ ⟨k, l⟩
  simp only [Matrix.stdBasis_eq_single, lie_single, map_sub, apply_ite L.toGlHomLinear,
    map_zero, toGlHomLinear_single, L.lie_E i j k l]

/-- The `gl(d)`-representation on `V` generated by a ladder system, bundled as a `LieHom`. -/
noncomputable def toGlHom (L : LadderSystem K V d) :
    Matrix (Fin d) (Fin d) K →ₗ⁅K⁆ Module.End K V :=
  { L.toGlHomLinear with map_lie' := L.toGlHomLinear_lie _ _ }

/-- `V` as a `gl(d)`-module, the `LieRingModule` instance (not global -- depends on `L`; use via
`haveI := L.toLieRingModule`). -/
@[reducible] noncomputable def toLieRingModule (L : LadderSystem K V d) :
    LieRingModule (Matrix (Fin d) (Fin d) K) V :=
  LieRingModule.compLieHom V L.toGlHom

/-- The companion `LieModule` instance. -/
theorem toLieModule (L : LadderSystem K V d) :
    @LieModule K (Matrix (Fin d) (Fin d) K) V _ _ _ _ _ L.toLieRingModule :=
  LieModule.compLieHom V L.toGlHom

/-!

## C. The number operator

-/

/-- The number operator for mode `i`, `Nᵢ ≔ Eᵢᵢ = acᵢaᵢ`. -/
def N (i : Fin d) : Module.End K V := L.E i i

/-!

### C.1. Commutation relations

-/

/-- `[Nᵢ, aⱼ] = -δᵢⱼaᵢ`. -/
theorem lie_N_a (i j : Fin d) :
    (⁅L.N i, L.a j⁆ : Module.End K V) =
      (if i = j then (-1 : Module.End K V) else 0) * L.a i := by
  show (⁅L.ac i * L.a i, L.a j⁆ : Module.End K V) = _
  rw [assoc_leibniz' (L.ac i) (L.a i) (L.a j), L.comm_a_a i j, mul_zero, zero_add]
  have h : (⁅L.ac i, L.a j⁆ : Module.End K V) =
      -(if j = i then (1 : Module.End K V) else 0) := by
    rw [← lie_skew, L.comm_a_ac j i]
  rw [h]
  rcases eq_or_ne i j with rfl | hij
  · simp
  · rw [if_neg hij, if_neg (Ne.symm hij)]
    simp

/-- `[Nᵢ, acⱼ] = δᵢⱼacᵢ`. -/
theorem lie_N_ac (i j : Fin d) :
    (⁅L.N i, L.ac j⁆ : Module.End K V) =
      (if i = j then (1 : Module.End K V) else 0) * L.ac i := by
  show (⁅L.ac i * L.a i, L.ac j⁆ : Module.End K V) = _
  rw [assoc_leibniz' (L.ac i) (L.a i) (L.ac j), L.comm_a_ac i j, L.comm_ac_ac i j, zero_mul,
    add_zero]
  rcases eq_or_ne i j with rfl | hij
  · simp
  · simp [hij]

/-- `[Nᵢ, Nⱼ] = 0`: the number operators commute among themselves. -/
theorem lie_N_N (i j : Fin d) : (⁅L.N i, L.N j⁆ : Module.End K V) = 0 := by
  rcases eq_or_ne i j with rfl | hij
  · exact lie_self _
  · show (⁅L.ac i * L.a i, L.N j⁆ : Module.End K V) = 0
    rw [assoc_leibniz' (L.ac i) (L.a i) (L.N j),
      ← lie_skew (L.a i) (L.N j), lie_N_a, ← lie_skew (L.ac i) (L.N j), lie_N_ac]
    simp [Ne.symm hij]

end LadderSystem
