/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Physlib.Mathematics.OneParameterSubgroups.Basic

/-!

# Unitary one-parameter groups

A norm-continuous unitary one-parameter group on a complex Hilbert space has a unique bounded
self-adjoint generator. With the convention used here, the group generated by `A` is
`U(t) = exp (-itA)`.

The same correspondence describes bounded generators of time translations, spatial translations,
rotations, and other norm-continuous unitary one-parameter groups. The general theorem for strongly
continuous groups and unbounded generators requires spectral theory that is not yet available in
Physlib.

## Main results

* `UnitaryOneParameterGroup.generator`: The canonical bounded self-adjoint generator.
* `UnitaryOneParameterGroup.apply_eq_exp_generator`: The formula `U(t) = exp (-itA)`.
* `UnitaryOneParameterGroup.ofSelfAdjoint`: The group generated by a bounded self-adjoint operator.
* `UnitaryOneParameterGroup.stoneEquiv`: Stone's correspondence for bounded generators.

## References

* M. H. Stone, *Linear Transformations in Hilbert Space III. Operational Methods and Group Theory*,
  Proc. Natl. Acad. Sci. 18 (1932), 172-175.

-/

@[expose] public section

noncomputable section

/-- A norm-continuous unitary one-parameter group on a complex Hilbert space. -/
structure UnitaryOneParameterGroup (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] where
  /-- The additive character from the real parameter to unitary operators. -/
  toAddChar : AddChar ℝ (H →L[ℂ] H)
  /-- The group is valued in the unitary operators on `H`. -/
  mem_unitary : ∀ t, toAddChar t ∈ unitary (H →L[ℂ] H)
  /-- The group is continuous in the operator norm. -/
  continuous : Continuous toAddChar

namespace UnitaryOneParameterGroup

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

attribute [coe] UnitaryOneParameterGroup.toAddChar

instance : CoeFun (UnitaryOneParameterGroup H) fun _ => ℝ → (H →L[ℂ] H) :=
  ⟨fun U => U.toAddChar⟩

@[ext]
lemma ext {U V : UnitaryOneParameterGroup H} (h : ∀ t, U t = V t) : U = V := by
  cases U
  cases V
  congr
  exact AddChar.ext _ _ h

lemma apply_eq_exp_deriv (U : UnitaryOneParameterGroup H) (t : ℝ) :
    U t = NormedSpace.exp ((t : ℂ) • deriv U 0) :=
  OneParameterSubgroup.apply_eq_exp_smul_deriv U.toAddChar U.continuous t

@[simp]
lemma adjoint_eq (U : UnitaryOneParameterGroup H) (t : ℝ) : (U t).adjoint = U (-t) := by
  apply left_inv_eq_right_inv (Unitary.star_mul_self_of_mem (U.mem_unitary t))
  simp [← AddChar.map_add_eq_mul]

/-- The bounded self-adjoint generator of `U`, in the convention `U(t) = exp (-itA)`. -/
noncomputable def generator (U : UnitaryOneParameterGroup H) : H →L[ℂ] H :=
  Complex.I • deriv U 0

lemma apply_eq_exp_generator (U : UnitaryOneParameterGroup H) (t : ℝ) :
    U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • U.generator) := by
  rw [U.apply_eq_exp_deriv]
  apply congrArg NormedSpace.exp
  rw [generator, smul_smul]
  apply congrArg (fun z : ℂ => z • deriv U 0)
  rw [mul_assoc, Complex.I_mul_I]
  simp

/-- Any exponential generator of a unitary one-parameter group equals `U.generator`; the
uniqueness of the derivative at zero (`OneParameterSubgroup.generator_unique`) is the underlying
fact, restated here in terms of the physics convention. -/
lemma generator_unique (U : UnitaryOneParameterGroup H) (A : H →L[ℂ] H)
    (h : ∀ t : ℝ, U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • A)) :
    A = U.generator := by
  have hrep : ∀ t : ℝ, U t =
      NormedSpace.exp ((t : ℂ) • ((-Complex.I) • A)) := by
    intro t
    rw [h t]
    congr 1
    rw [smul_smul]
    congr 1
    ring
  have hderiv : (-Complex.I) • A = deriv U 0 :=
    OneParameterSubgroup.generator_unique U.toAddChar ((-Complex.I) • A)
      (fun t => by simpa only [Complex.coe_smul] using hrep t)
  calc
    A = Complex.I • ((-Complex.I) • A) := by rw [smul_smul]; simp
    _ = Complex.I • deriv U 0 := by rw [hderiv]
    _ = U.generator := rfl

lemma adjoint_deriv_eq_neg (U : UnitaryOneParameterGroup H) :
    (deriv U 0).adjoint = -deriv U 0 := by
  let A : H →L[ℂ] H := deriv U 0
  refine (neg_eq_iff_eq_neg.mpr ?_).symm
  refine (OneParameterSubgroup.generator_unique U.toAddChar (-A.adjoint) fun t ↦ ?_).symm
  calc
    _ = (U (-t)).adjoint := by simp
    _ = (NormedSpace.exp (((-t : ℝ) : ℂ) • A)).adjoint := by simp [A, U.apply_eq_exp_deriv]
    _ = NormedSpace.exp (((-t : ℝ) : ℂ) • A).adjoint := NormedSpace.star_exp _
    _ = NormedSpace.exp (t • -A.adjoint) := by
      simp [← ContinuousLinearMap.star_eq_adjoint, Complex.coe_smul]

/-- The generator of a unitary one-parameter group is self-adjoint. -/
lemma generator_isSelfAdjoint (U : UnitaryOneParameterGroup H) : IsSelfAdjoint U.generator := by
  apply IsSelfAdjoint.I_smul_of_mem_skewAdjoint
  rw [skewAdjoint.mem_iff]
  exact U.adjoint_deriv_eq_neg

/-- The unitary one-parameter group generated by a bounded self-adjoint operator. -/
def ofSelfAdjoint {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) :
    UnitaryOneParameterGroup H := by
  letI : NormedAlgebra ℚ (H →L[ℂ] H) := .restrictScalars ℚ ℂ (H →L[ℂ] H)
  exact {
    toAddChar := {
      toFun t := NormedSpace.exp ((t : ℂ) • (-Complex.I • A))
      map_zero_eq_one' := by simp
      map_add_eq_mul' s t := by
        have hcomm : Commute ((s : ℂ) • (-Complex.I • A)) ((t : ℂ) • (-Complex.I • A)) :=
          ((Commute.refl (-Complex.I • A)).smul_left _).smul_right _
        rw [← NormedSpace.exp_add_of_commute hcomm]
        simp [add_smul, add_comm]
      }
    mem_unitary t := by
      apply NormedSpace.exp_mem_unitary_of_mem_skewAdjoint
      simp [skewAdjoint.mem_iff, hA.star_eq]
    continuous := by
      change Continuous (fun t : ℝ => NormedSpace.exp ((t : ℂ) • (-Complex.I • A)))
      fun_prop
  }

@[simp]
lemma ofSelfAdjoint_apply {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) (t : ℝ) :
    ofSelfAdjoint hA t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • A) := by
  simp only [ofSelfAdjoint]
  change NormedSpace.exp ((t : ℂ) • ((-Complex.I) • A)) = _
  rw [smul_smul]
  ring_nf

/-- `ofSelfAdjoint` recovers `U` from its own generator: this is the defining property used to
show `stoneEquiv` is a left inverse. -/
@[simp]
lemma ofSelfAdjoint_generator (U : UnitaryOneParameterGroup H) :
    ofSelfAdjoint U.generator_isSelfAdjoint = U := by
  apply ext
  intro t
  rw [ofSelfAdjoint_apply, U.apply_eq_exp_generator]

/-- The generator of `ofSelfAdjoint hA` is `A` itself: this is the defining property used to show
`stoneEquiv` is a right inverse. -/
@[simp]
lemma generator_ofSelfAdjoint {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) :
    (ofSelfAdjoint hA).generator = A :=
  ((ofSelfAdjoint hA).generator_unique A (ofSelfAdjoint_apply hA)).symm

/-- Stone's correspondence between norm-continuous unitary one-parameter groups and bounded
self-adjoint generators. -/
noncomputable def stoneEquiv :
    UnitaryOneParameterGroup H ≃ {A : H →L[ℂ] H // IsSelfAdjoint A} where
  toFun U := ⟨U.generator, U.generator_isSelfAdjoint⟩
  invFun A := ofSelfAdjoint A.2
  left_inv _ := by simp
  right_inv _ := by simp

/-! ## Differential equation

`U` and its adjoint each satisfy a differential equation in the generator, shared by every
norm-continuous unitary one-parameter group regardless of what generates it (a Hamiltonian, a
momentum operator, an angular momentum, ...). -/

/-- The real-scalar structure `H →L[ℂ] H` needs to state `HasDerivAt` over `ℝ` (the differential
equation below differentiates in the real time parameter `t`), obtained by restricting the
ambient `ℂ`-algebra structure along `ℝ ⊆ ℂ`. -/
noncomputable local instance : NormedAlgebra ℝ (H →L[ℂ] H) :=
  { NormedSpace.complexToReal, NormedAlgebra.complexToReal with }

omit [CompleteSpace H] in
/-- Real and complex scalar multiplication agree on `H →L[ℂ] H` after casting; needed because the
derivative below mixes a real time parameter with the complex generator. -/
private lemma real_smul_eq_complex_smul (t : ℝ) (x : H →L[ℂ] H) :
    t • x = (t : ℂ) • x := by
  have h : (t : ℂ) = algebraMap ℝ ℂ t := by norm_cast
  rw [h, IsScalarTower.algebraMap_smul]

/-- `U'(t) = U(t) · (-i • generator)`: rewrite `U` as `exp(s • (-i • generator))` and
differentiate the exponential. -/
lemma hasDerivAt (U : UnitaryOneParameterGroup H) (t : ℝ) :
    HasDerivAt (fun s : ℝ => U s) (U t * (-(Complex.I • U.generator))) t := by
  have heq : (fun s : ℝ => U s) =
      fun s : ℝ => NormedSpace.exp (s • (-(Complex.I • U.generator))) := by
    funext s
    rw [U.apply_eq_exp_generator]
    apply congrArg NormedSpace.exp
    rw [real_smul_eq_complex_smul, smul_neg, smul_smul, ← neg_smul]
    congr 1
    ring
  rw [heq, congrFun heq t]
  exact hasDerivAt_exp_smul_const (-(Complex.I • U.generator)) t

/-- `(U(t)⋆)' = U(t)⋆ · (i • generator)`: reduce to `hasDerivAt` via `U(t)⋆ = U(-t)`. -/
lemma hasDerivAt_star (U : UnitaryOneParameterGroup H) (t : ℝ) :
    HasDerivAt (fun s : ℝ => star (U s)) (star (U t) * (Complex.I • U.generator)) t := by
  have heq : (fun s : ℝ => star (U s)) =
      fun s : ℝ => NormedSpace.exp (s • (Complex.I • U.generator)) := by
    funext s
    have hs : star (U s) = U (-s) := by
      simpa [← ContinuousLinearMap.star_eq_adjoint] using U.adjoint_eq s
    rw [hs, U.apply_eq_exp_generator]
    apply congrArg NormedSpace.exp
    rw [real_smul_eq_complex_smul, smul_smul]
    congr 1
    push_cast
    ring
  rw [heq, congrFun heq t]
  exact hasDerivAt_exp_smul_const (Complex.I • U.generator) t

/-- The generator commutes with the unitary group it generates, since `U(t) = exp(t • generator)`
is built from `generator` alone. -/
lemma commute_generator (U : UnitaryOneParameterGroup H) (t : ℝ) :
    Commute U.generator (U t) := by
  rw [U.apply_eq_exp_generator]
  exact ((Commute.refl U.generator).smul_right (-(t : ℂ) * Complex.I)).exp_right

end UnitaryOneParameterGroup
