/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Physlib.Mathematics.OneParameterSubgroups.Basic

/-!

# Unitary one-parameter groups

A norm-continuous unitary one-parameter group on a complex Hilbert space has a unique bounded
self-adjoint generator. With the convention used here, the group generated by `A` is
`U(t) = exp (-itA)`.

The same correspondence describes bounded generators of time translations, spatial translations,
rotations, and other norm-continuous unitary one-parameter groups. The general theorem for strongly
continuous groups and unbounded generators requires spectral theory that is not yet available in
Physlib.

## Main results

* `UnitaryOneParameterGroup.generator`: The canonical bounded self-adjoint generator.
* `UnitaryOneParameterGroup.apply_eq_exp_generator`: The formula `U(t) = exp (-itA)`.
* `UnitaryOneParameterGroup.ofSelfAdjoint`: The group generated by a bounded self-adjoint operator.
* `UnitaryOneParameterGroup.stoneEquiv`: Stone's correspondence for bounded generators.

## References

* M. H. Stone, *Linear Transformations in Hilbert Space III. Operational Methods and Group Theory*,
  Proc. Natl. Acad. Sci. 18 (1932), 172-175.

-/

@[expose] public section

noncomputable section

/-- A norm-continuous unitary one-parameter group on a complex Hilbert space. -/
structure UnitaryOneParameterGroup (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] where
  /-- The additive character from the real parameter to unitary operators. -/
  toAddChar : AddChar ℝ (unitary (H →L[ℂ] H))
  /-- The group is continuous in the operator norm. -/
  continuous : Continuous toAddChar

namespace UnitaryOneParameterGroup

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

instance : CoeFun (UnitaryOneParameterGroup H) fun _ => ℝ → (H →L[ℂ] H) :=
  ⟨fun U t => U.toAddChar t⟩

/-- The operator-valued additive character underlying a unitary one-parameter group. -/
def operatorAddChar (U : UnitaryOneParameterGroup H) : AddChar ℝ (H →L[ℂ] H) :=
  (unitary (H →L[ℂ] H)).subtype.compAddChar U.toAddChar

@[simp]
lemma operatorAddChar_apply (U : UnitaryOneParameterGroup H) (t : ℝ) :
    U.operatorAddChar t = U t := rfl

lemma continuous_operatorAddChar (U : UnitaryOneParameterGroup H) :
    Continuous U.operatorAddChar :=
  continuous_subtype_val.comp U.continuous

@[ext]
lemma ext {U V : UnitaryOneParameterGroup H} (h : ∀ t, U t = V t) : U = V := by
  cases U
  cases V
  congr
  exact AddChar.ext _ _ fun t => Subtype.ext (h t)

@[simp]
lemma adjoint_eq (U : UnitaryOneParameterGroup H) (t : ℝ) :
    ContinuousLinearMap.adjoint (U t) = U (-t) := by
  change star (U t) = U (-t)
  apply left_inv_eq_right_inv (U.toAddChar t).property.1
  have h := congrArg Subtype.val (U.toAddChar.map_add_eq_mul t (-t))
  simpa using h.symm

/-- The bounded self-adjoint generator of `U`, in the convention `U(t) = exp (-itA)`. -/
noncomputable def generator (U : UnitaryOneParameterGroup H) : H →L[ℂ] H :=
  Complex.I • deriv U.operatorAddChar 0

lemma deriv_star_eq_neg (U : UnitaryOneParameterGroup H) :
    star (deriv U.operatorAddChar 0) = -deriv U.operatorAddChar 0 := by
  let A : H →L[ℂ] H := deriv U.operatorAddChar 0
  have hA (t : ℝ) : U t = NormedSpace.exp ((t : ℂ) • A) := by
    change U.operatorAddChar t = _
    dsimp only [A]
    simpa only [Complex.coe_smul] using
      OneParameterSubgroup.apply_eq_exp_smul_deriv U.operatorAddChar
        U.continuous_operatorAddChar t
  have hrep : ∀ t : ℝ, U.operatorAddChar t =
      NormedSpace.exp ((t : ℂ) • (-star A)) := by
    intro t
    calc
      U.operatorAddChar t = star (U (-t)) := by
        change U t = ContinuousLinearMap.adjoint (U (-t))
        simpa only [neg_neg] using (U.adjoint_eq (-t)).symm
      _ = star (NormedSpace.exp (((-t : ℝ) : ℂ) • A)) := by rw [hA (-t)]
      _ = NormedSpace.exp (star (((-t : ℝ) : ℂ) • A)) := NormedSpace.star_exp _
      _ = NormedSpace.exp ((t : ℂ) • (-star A)) := by
        congr 1
        simp [star_smul]
  have hgen : -star A = A :=
    OneParameterSubgroup.generator_unique U.operatorAddChar (-star A) fun t => by
      simpa only [Complex.coe_smul] using hrep t
  simpa [A] using congrArg Neg.neg hgen

/-- The generator of a unitary one-parameter group is self-adjoint. -/
lemma generator_selfAdjoint (U : UnitaryOneParameterGroup H) : IsSelfAdjoint U.generator := by
  apply IsSelfAdjoint.I_smul_of_mem_skewAdjoint
  rw [skewAdjoint.mem_iff, U.deriv_star_eq_neg]

/-- A unitary one-parameter group is the exponential of its self-adjoint generator. -/
@[simp]
lemma apply_eq_exp_generator (U : UnitaryOneParameterGroup H) (t : ℝ) :
    U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • U.generator) := by
  change U.operatorAddChar t = _
  rw [OneParameterSubgroup.apply_eq_exp_smul_deriv U.operatorAddChar
    U.continuous_operatorAddChar]
  apply congrArg NormedSpace.exp
  rw [generator, smul_smul]
  apply congrArg (fun z : ℂ => z • deriv U.operatorAddChar 0)
  rw [mul_assoc, Complex.I_mul_I]
  simp

/-- An operator representing `U` as `exp (-itA)` is its generator. -/
lemma generator_unique (U : UnitaryOneParameterGroup H) (A : H →L[ℂ] H)
    (h : ∀ t : ℝ, U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • A)) :
    A = U.generator := by
  have hrep : ∀ t : ℝ, U.operatorAddChar t =
      NormedSpace.exp (t • ((-Complex.I) • A)) := by
    intro t
    change U t = _
    rw [h t]
    congr 1
    rw [← Complex.coe_smul, smul_smul]
    apply congrArg (fun z : ℂ => z • A)
    ring
  have hderiv : (-Complex.I) • A = deriv U.operatorAddChar 0 :=
    OneParameterSubgroup.generator_unique U.operatorAddChar ((-Complex.I) • A) hrep
  calc
    A = Complex.I • ((-Complex.I) • A) := by rw [smul_smul]; simp
    _ = Complex.I • deriv U.operatorAddChar 0 := by rw [hderiv]
    _ = U.generator := rfl

/-- The unitary one-parameter group generated by a bounded self-adjoint operator. -/
def ofSelfAdjoint {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) :
    UnitaryOneParameterGroup H := by
  letI : NormedAlgebra ℚ (H →L[ℂ] H) := .restrictScalars ℚ ℂ (H →L[ℂ] H)
  let B : H →L[ℂ] H := (-Complex.I) • A
  have hB : star B = -B := by
    dsimp [B]
    rw [star_smul, Complex.star_def, map_neg, Complex.conj_I, hA.star_eq]
    module
  let U : AddChar ℝ (unitary (H →L[ℂ] H)) := {
    toFun t := ⟨NormedSpace.exp ((t : ℂ) • B), by
      apply NormedSpace.exp_mem_unitary_of_mem_skewAdjoint
      rw [skewAdjoint.mem_iff, star_smul, Complex.star_def, Complex.conj_ofReal, hB]
      module⟩
    map_zero_eq_one' := by ext; simp
    map_add_eq_mul' := fun s t => by
      apply Subtype.ext
      have hcomm : Commute ((s : ℂ) • B) ((t : ℂ) • B) :=
        ((Commute.refl B).smul_left _).smul_right _
      change NormedSpace.exp (((s + t : ℝ) : ℂ) • B) =
        NormedSpace.exp ((s : ℂ) • B) * NormedSpace.exp ((t : ℂ) • B)
      rw [← NormedSpace.exp_add_of_commute hcomm]
      push_cast
      rw [add_smul] }
  exact ⟨U, Continuous.subtype_mk (by
    change Continuous (fun t : ℝ => NormedSpace.exp ((t : ℂ) • B))
    fun_prop) _⟩

@[simp]
lemma ofSelfAdjoint_apply {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) (t : ℝ) :
    ofSelfAdjoint hA t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • A) := by
  simp only [ofSelfAdjoint]
  change NormedSpace.exp ((t : ℂ) • ((-Complex.I) • A)) = _
  rw [smul_smul]
  congr 1
  ring_nf

/-- Stone's correspondence between norm-continuous unitary one-parameter groups and bounded
self-adjoint generators. -/
noncomputable def stoneEquiv :
    UnitaryOneParameterGroup H ≃ {A : H →L[ℂ] H // IsSelfAdjoint A} where
  toFun U := ⟨U.generator, U.generator_selfAdjoint⟩
  invFun A := ofSelfAdjoint A.2
  left_inv U := by
    apply ext
    intro t
    rw [ofSelfAdjoint_apply, U.apply_eq_exp_generator]
  right_inv A := by
    apply Subtype.ext
    exact ((ofSelfAdjoint A.2).generator_unique A.1 (ofSelfAdjoint_apply A.2)).symm

end UnitaryOneParameterGroup
