/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Physlib.Mathematics.OneParameterSubgroups.Basic
public import Physlib.Mathematics.OneParameterSubgroups.Rotation

/-!

# Unitary one-parameter groups

A norm-continuous unitary one-parameter group on a complex Hilbert space has a unique bounded
self-adjoint generator. With the convention used here, the group generated by `A` is
`U(t) = exp (-itA)`.

The same correspondence describes bounded generators of time translations, spatial translations,
rotations, and other norm-continuous unitary one-parameter groups. The general theorem for strongly
continuous groups and unbounded generators requires spectral theory that is not yet available in
Physlib.

## Main results

* `UnitaryOneParameterGroup.generator`: The canonical bounded self-adjoint generator.
* `UnitaryOneParameterGroup.apply_eq_exp_generator`: The formula `U(t) = exp (-itA)`.
* `UnitaryOneParameterGroup.ofSelfAdjoint`: The group generated by a bounded self-adjoint operator.
* `UnitaryOneParameterGroup.stoneEquiv`: Stone's correspondence for bounded generators.
* `UnitaryOneParameterGroup.ofSelfAdjoint_apply_of_sq_eq_smul_one`: whenever the generator `A`
  squares to a real multiple of the identity, `A² = r² • 1`, the group it generates has the
  familiar closed form `U(t) = cos(rt) • 1 - i sin(rt) • A`. This is the general fact behind every
  "rotation generated by an involution" computation (e.g. spin precession about a Pauli vector).

## References

* M. H. Stone, *Linear Transformations in Hilbert Space III. Operational Methods and Group Theory*,
  Proc. Natl. Acad. Sci. 18 (1932), 172-175.

-/

@[expose] public section

noncomputable section

/-- A norm-continuous unitary one-parameter group on a complex Hilbert space. -/
structure UnitaryOneParameterGroup (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] where
  /-- The additive character from the real parameter to unitary operators. -/
  toAddChar : AddChar ℝ (H →L[ℂ] H)
  /-- The group is valued in the unitary operators on `H`. -/
  mem_unitary : ∀ t, toAddChar t ∈ unitary (H →L[ℂ] H)
  /-- The group is continuous in the operator norm. -/
  continuous : Continuous toAddChar

namespace UnitaryOneParameterGroup

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

attribute [coe] UnitaryOneParameterGroup.toAddChar

instance : CoeFun (UnitaryOneParameterGroup H) fun _ => ℝ → (H →L[ℂ] H) := ⟨fun U => U.toAddChar⟩

@[ext]
lemma ext {U V : UnitaryOneParameterGroup H} (h : ∀ t, U t = V t) : U = V := by
  cases U
  cases V
  congr
  exact AddChar.ext _ _ h

lemma apply_eq_exp_deriv (U : UnitaryOneParameterGroup H) (t : ℝ) :
    U t = NormedSpace.exp ((t : ℂ) • deriv U 0) :=
  OneParameterSubgroup.apply_eq_exp_smul_deriv U.toAddChar U.continuous t

@[simp]
lemma adjoint_eq (U : UnitaryOneParameterGroup H) (t : ℝ) : (U t).adjoint = U (-t) := by
  apply left_inv_eq_right_inv (Unitary.star_mul_self_of_mem (U.mem_unitary t))
  simp [← AddChar.map_add_eq_mul]

/-- The bounded self-adjoint generator of `U`, in the convention `U(t) = exp (-itA)`. -/
noncomputable def generator (U : UnitaryOneParameterGroup H) : H →L[ℂ] H :=
  Complex.I • deriv U 0

lemma apply_eq_exp_generator (U : UnitaryOneParameterGroup H) (t : ℝ) :
    U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • U.generator) := by
  rw [U.apply_eq_exp_deriv]
  apply congrArg NormedSpace.exp
  rw [generator, smul_smul]
  apply congrArg (fun z : ℂ => z • deriv U 0)
  rw [mul_assoc, Complex.I_mul_I]
  simp

/-- Any exponential generator of a unitary one-parameter group equals `U.generator`; the
uniqueness of the derivative at zero (`OneParameterSubgroup.generator_unique`) is the underlying
fact, restated here in terms of the physics convention. -/
lemma generator_unique (U : UnitaryOneParameterGroup H) (A : H →L[ℂ] H)
    (h : ∀ t : ℝ, U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • A)) :
    A = U.generator := by
  have hrep : ∀ t : ℝ, U t =
      NormedSpace.exp ((t : ℂ) • ((-Complex.I) • A)) := by
    intro t
    rw [h t]
    congr 1
    rw [smul_smul]
    congr 1
    ring
  have hderiv : (-Complex.I) • A = deriv U 0 :=
    OneParameterSubgroup.generator_unique U.toAddChar ((-Complex.I) • A)
      (fun t => by simpa only [Complex.coe_smul] using hrep t)
  calc
    A = Complex.I • ((-Complex.I) • A) := by rw [smul_smul]; simp
    _ = Complex.I • deriv U 0 := by rw [hderiv]
    _ = U.generator := rfl

lemma adjoint_deriv_eq_neg (U : UnitaryOneParameterGroup H) :
    (deriv U 0).adjoint = -deriv U 0 := by
  let A : H →L[ℂ] H := deriv U 0
  have hrep : ∀ t : ℝ, U t =
      NormedSpace.exp ((t : ℂ) • (-star A)) := by
    intro t
    calc
      U t = star (U (-t)) := by
        change U t = ContinuousLinearMap.adjoint (U (-t))
        simpa only [neg_neg] using (U.adjoint_eq (-t)).symm
      _ = star (NormedSpace.exp (((-t : ℝ) : ℂ) • A)) := by rw [U.apply_eq_exp_deriv]
      _ = NormedSpace.exp (star (((-t : ℝ) : ℂ) • A)) := NormedSpace.star_exp _
      _ = NormedSpace.exp ((t : ℂ) • (-star A)) := by
        congr 1
        simp [star_smul]
  have hgen : A = -star A :=
    (OneParameterSubgroup.generator_unique U.toAddChar (-star A)
      (fun t => by simpa only [Complex.coe_smul] using hrep t)).symm
  change star A = -A
  exact (neg_eq_iff_eq_neg.mpr hgen).symm

/-- The generator of a unitary one-parameter group is self-adjoint. -/
lemma generator_isSelfAdjoint (U : UnitaryOneParameterGroup H) : IsSelfAdjoint U.generator := by
  apply IsSelfAdjoint.I_smul_of_mem_skewAdjoint
  rw [skewAdjoint.mem_iff]
  exact U.adjoint_deriv_eq_neg

/-- The unitary one-parameter group generated by a bounded self-adjoint operator. -/
def ofSelfAdjoint {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) :
    UnitaryOneParameterGroup H := by
  letI : NormedAlgebra ℚ (H →L[ℂ] H) := .restrictScalars ℚ ℂ (H →L[ℂ] H)
  let B : H →L[ℂ] H := (-Complex.I) • A
  have hB : star B = -B := by
    dsimp [B]
    rw [star_smul, Complex.star_def, map_neg, Complex.conj_I, hA.star_eq]
    module
  let U : AddChar ℝ (H →L[ℂ] H) := {
    toFun t := NormedSpace.exp ((t : ℂ) • B)
    map_zero_eq_one' := by simp
    map_add_eq_mul' := fun s t => by
      have hcomm : Commute ((s : ℂ) • B) ((t : ℂ) • B) :=
        ((Commute.refl B).smul_left _).smul_right _
      change NormedSpace.exp (((s + t : ℝ) : ℂ) • B) =
        NormedSpace.exp ((s : ℂ) • B) * NormedSpace.exp ((t : ℂ) • B)
      rw [← NormedSpace.exp_add_of_commute hcomm]
      push_cast
      rw [add_smul] }
  refine {
    toAddChar := U
    mem_unitary := ?_
    continuous := ?_
  }
  · intro t
    dsimp [U]
    apply NormedSpace.exp_mem_unitary_of_mem_skewAdjoint
    rw [skewAdjoint.mem_iff]
    simp [hB]
  · dsimp [U]
    change Continuous (fun t : ℝ => NormedSpace.exp ((t : ℂ) • B))
    fun_prop

@[simp]
lemma ofSelfAdjoint_apply {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) (t : ℝ) :
    ofSelfAdjoint hA t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • A) := by
  simp only [ofSelfAdjoint]
  change NormedSpace.exp ((t : ℂ) • ((-Complex.I) • A)) = _
  rw [smul_smul]
  congr 1
  ring_nf

/-- `ofSelfAdjoint` recovers `U` from its own generator: this is the defining property used to
show `stoneEquiv` is a left inverse. -/
@[simp]
lemma ofSelfAdjoint_generator (U : UnitaryOneParameterGroup H) :
    ofSelfAdjoint U.generator_isSelfAdjoint = U := by
  apply ext
  intro t
  rw [ofSelfAdjoint_apply, U.apply_eq_exp_generator]

/-- The generator of `ofSelfAdjoint hA` is `A` itself: this is the defining property used to show
`stoneEquiv` is a right inverse. -/
@[simp]
lemma generator_ofSelfAdjoint {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) :
    (ofSelfAdjoint hA).generator = A :=
  ((ofSelfAdjoint hA).generator_unique A (ofSelfAdjoint_apply hA)).symm

/-- Stone's correspondence between norm-continuous unitary one-parameter groups and bounded
self-adjoint generators. -/
noncomputable def stoneEquiv :
    UnitaryOneParameterGroup H ≃ {A : H →L[ℂ] H // IsSelfAdjoint A} where
  toFun U := ⟨U.generator, U.generator_isSelfAdjoint⟩
  invFun A := ofSelfAdjoint A.2
  left_inv _ := by simp
  right_inv _ := by simp


/-!
## Closed form for self-adjoint generators

If the self-adjoint generator `A` satisfies `A² = r² • 1`, the skew-adjoint operator `K := -iA`
satisfies `K² = -r² • 1`, so `exp(sK)` is a direct instance of the general rotation identity
`NormedSpace.exp_smul_of_sq_eq_neg_smul_one` (`Mathematics.OneParameterSubgroups.Rotation`), the
real-Banach-algebra analogue of Euler's formula. No separate series computation is needed here:
the "complex phase" in `exp(-isA) = cos(rs) • 1 - i sin(rs)/r • A` is entirely accounted for by
the substitution `K = -iA`, not by redoing the even/odd series splitting for this case.
-/

/-- The exponential of a scalar multiple of the identity is the scalar exponential. -/
lemma _root_.ContinuousLinearMap.exp_smul_one (z : ℂ) :
    NormedSpace.exp (z • (1 : H →L[ℂ] H)) = Complex.exp z • 1 := by
  change NormedSpace.exp (algebraMap ℂ (H →L[ℂ] H) z) = _
  rw [← NormedSpace.algebraMap_exp_comm, Complex.exp_eq_exp_ℂ]
  simp [Algebra.algebraMap_eq_smul_one]

/-- If `A² = r² • 1`, then `exp (-isA) = cos (rs) • 1 - i sin (rs)/r • A`: this is the general
fact behind every "rotation generated by a self-adjoint involution" computation (e.g. spin
precession about a Pauli vector), obtained from `NormedSpace.exp_smul_of_sq_eq_neg_smul_one`
applied to the skew-adjoint generator `K := -iA`. -/
lemma _root_.ContinuousLinearMap.exp_neg_I_smul_of_sq_eq_smul_one {A : H →L[ℂ] H}
    (hA : IsSelfAdjoint A) (r : ℝ) (hsq : A * A = (r ^ 2 : ℝ) • 1) (s : ℝ) :
    NormedSpace.exp ((-(s : ℂ) * Complex.I) • A) =
      (Real.cos (r * s) : ℂ) • 1 - ((Real.sin (r * s) : ℂ) * Complex.I / r) • A := by
  by_cases hr : r = 0
  · have hnorm : ‖A‖ * ‖A‖ = 0 := by
      rw [← CStarRing.norm_star_mul_self, hA.star_eq, hsq, hr]
      simp
    have hA0 : A = 0 := norm_eq_zero.mp (mul_self_eq_zero.mp hnorm)
    simp [hA0, hr]
  · have hK2 : ((-Complex.I) • A) * ((-Complex.I) • A) = (-(r ^ 2) : ℝ) • (1 : H →L[ℂ] H) := by
      rw [smul_mul_smul, neg_mul_neg, Complex.I_mul_I, hsq, neg_one_smul, neg_smul]
    rw [show (-(s : ℂ) * Complex.I) • A = s • ((-Complex.I) • A) by
      rw [← Complex.coe_smul, smul_smul, neg_mul_comm],
      NormedSpace.exp_smul_of_sq_eq_neg_smul_one _ r hr hK2 s,
      ← Complex.coe_smul (Real.sin (r * s) / r) ((-Complex.I) • A), smul_smul, Complex.ofReal_div,
      sub_eq_add_neg, ← neg_smul]
    congr 2
    ring

/-- If the self-adjoint generator `A` satisfies `A² = r² • 1`, the one-parameter group it
generates has the familiar cosine-sine closed form `U(t) = cos(rt) • 1 - i sin(rt) • A`
(interpreting `sin(rt)/r` as `0` when `r = 0`, which is consistent since `A = 0` in that case). -/
theorem ofSelfAdjoint_apply_of_sq_eq_smul_one {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) (r : ℝ)
    (hsq : A * A = (r ^ 2 : ℝ) • 1) (t : ℝ) :
    ofSelfAdjoint hA t =
      (Real.cos (r * t) : ℂ) • 1 - ((Real.sin (r * t) : ℂ) * Complex.I / r) • A := by
  rw [ofSelfAdjoint_apply, ContinuousLinearMap.exp_neg_I_smul_of_sq_eq_smul_one hA r hsq]

end UnitaryOneParameterGroup
