/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Physlib.Mathematics.OneParameterSubgroups.Rotation
public import Mathlib.Analysis.CStarAlgebra.Matrix

/-!

# The classical harmonic oscillator: phase space and Hamiltonian flow

The mechanical layer of the classical harmonic oscillator, entirely independent of the
operator-algebra formalization built on top of it in the rest of this directory: phase space, the
Hamiltonian, and the linear flow it generates.

This is a separate development from `ClassicalMechanics.HarmonicOscillator.Basic`, which treats
the oscillator through the calculus of variations (`EulerLagrange`, `HamiltonsEquations`) on a
one-dimensional configuration space. Here phase space itself, `(q, p)`, is the basic object, and
the flow is obtained in closed form directly from the linearity of Hamilton's equations, without
appealing to any general existence theorem for Hamiltonian flows.

## Main definitions

* `PhaseSpace`: position-momentum phase space, `EuclideanSpace ℝ (Fin 2)`.
* `Hamiltonian m ω`: the energy function `H(q, p) = p² / 2m + mω²q² / 2`. Not an element of any
  observable algebra: it belongs to the smooth mechanical layer, not the algebraic layer.
* `K m ω`: the generator of Hamilton's equations, `K = [[0, 1/m], [-mω², 0]]`.
* `flow m ω t`: the Hamiltonian flow at time `t`, `Φ_t = exp(tK)`.
* `flowMatrix m ω t`: the matrix of `flow m ω t`, in closed rotation form.

## Main results

* `K_sq`: `K² = -ω² • 1`.
* `flow_eq`: the closed form `flow m ω t = cos(ωt) • 1 + (sin(ωt)/ω) • K`, transported from
  `Mathematics.OneParameterSubgroups.Rotation` to phase space.
* `flow_zero`, `flow_add`: the flow is a one-parameter group of linear maps.

-/

@[expose] public section

noncomputable section

open scoped Matrix.Norms.L2Operator

namespace ClassicalMechanics.HarmonicOscillator.OperatorAlgebra

/-- Phase space of the harmonic oscillator: position and momentum `(q, p)`. -/
abbrev PhaseSpace := EuclideanSpace ℝ (Fin 2)

namespace PhaseSpace

/-- The position coordinate. -/
def q (x : PhaseSpace) : ℝ := x 0

/-- The momentum coordinate. -/
def p (x : PhaseSpace) : ℝ := x 1

/-- Build a phase-space point from its position and momentum coordinates. -/
def mk (q p : ℝ) : PhaseSpace := !₂[q, p]

@[simp] lemma q_mk (q p : ℝ) : (mk q p).q = q := rfl

@[simp] lemma p_mk (q p : ℝ) : (mk q p).p = p := rfl

end PhaseSpace

variable (m ω : ℝ)

/-- The Hamiltonian (total mechanical energy) of the oscillator, `H(q,p) = p²/2m + mω²q²/2`. This
is a smooth function on phase space, *not* an element of the observable C⋆-algebra: it belongs to
the classical mechanical layer, not to the algebraic layer built on top of it. -/
def Hamiltonian (x : PhaseSpace) : ℝ :=
  x.p ^ 2 / (2 * m) + m * ω ^ 2 * x.q ^ 2 / 2

/-- The generator of Hamilton's equations, `q̇ = ∂H/∂p = p/m`, `ṗ = -∂H/∂q = -mω²q`, acting on
`(q, p)`. -/
def K : Matrix (Fin 2) (Fin 2) ℝ := !![0, 1 / m; -(m * ω ^ 2), 0]

lemma K_sq (hm : m ≠ 0) :
    K m ω * K m ω = (-(ω ^ 2) : ℝ) • (1 : Matrix (Fin 2) (Fin 2) ℝ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [K, Matrix.mul_apply, Fin.sum_univ_two] <;> field_simp

/-- The matrix of the flow, in closed rotation form. -/
def flowMatrix (t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  Real.cos (ω * t) • (1 : Matrix (Fin 2) (Fin 2) ℝ) + (Real.sin (ω * t) / ω) • K m ω

/-- The Hamiltonian flow at time `t`: the solution operator of Hamilton's equations,
`Φ_t = exp(tK)`. -/
def flow (t : ℝ) : PhaseSpace →L[ℝ] PhaseSpace :=
  NormedSpace.exp (t • Matrix.toEuclideanCLM (𝕜 := ℝ) (K m ω))

/-!
### Continuity, and compatibility with the exponential map

`Matrix.toEuclideanCLM`'s operator norm is definitionally the pushforward of the Euclidean operator
norm, so it is an isometry, hence continuous, hence commutes with `NormedSpace.exp`. This is what
lets the closed-form matrix rotation formula be transported to a statement about `flow`.
-/

private lemma toEuclideanCLM_continuous :
    Continuous (Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℝ)) :=
  (AddMonoidHomClass.isometry_of_norm _ (fun A => Matrix.cstar_norm_def A)).continuous

private lemma toEuclideanCLM_exp (x : Matrix (Fin 2) (Fin 2) ℝ) :
    Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℝ) (NormedSpace.exp x)
      = NormedSpace.exp (Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℝ) x) := by
  let _ : NormedAlgebra ℚ (Matrix (Fin 2) (Fin 2) ℝ) := .restrictScalars ℚ ℝ _
  let _ : NormedAlgebra ℚ (PhaseSpace →L[ℝ] PhaseSpace) := .restrictScalars ℚ ℝ _
  exact NormedSpace.map_exp (Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℝ))
    toEuclideanCLM_continuous x

/-- The flow at time `t` in closed form: a rotation generated by `K`, transported from the
generic matrix identity `NormedSpace.exp_smul_of_sq_eq_neg_smul_one` in
`Mathematics.OneParameterSubgroups.Rotation`. -/
theorem flow_eq (hm : m ≠ 0) (hω : ω ≠ 0) (t : ℝ) :
    flow m ω t = Matrix.toEuclideanCLM (𝕜 := ℝ) (flowMatrix m ω t) := by
  show NormedSpace.exp (t • Matrix.toEuclideanCLM (𝕜 := ℝ) (K m ω)) = _
  rw [show t • Matrix.toEuclideanCLM (𝕜 := ℝ) (K m ω)
      = Matrix.toEuclideanCLM (𝕜 := ℝ) (t • K m ω) from (map_smul _ t (K m ω)).symm,
    ← toEuclideanCLM_exp,
    NormedSpace.exp_smul_of_sq_eq_neg_smul_one (K m ω) ω hω (K_sq m ω hm) t]
  simp [flowMatrix, map_add, map_smul, map_one]

@[simp]
lemma flowMatrix_zero : flowMatrix m ω 0 = 1 := by simp [flowMatrix]

@[simp]
lemma flow_zero : flow m ω 0 = 1 := by
  show NormedSpace.exp ((0 : ℝ) • Matrix.toEuclideanCLM (𝕜 := ℝ) (K m ω)) = 1
  rw [zero_smul ℝ (Matrix.toEuclideanCLM (𝕜 := ℝ) (K m ω)), NormedSpace.exp_zero]

/-- The flow's matrix is a one-parameter group: pure trigonometric algebra on `2 × 2` matrices,
independently of the exponential-map machinery behind `flow_eq`. -/
lemma flowMatrix_add (hm : m ≠ 0) (s t : ℝ) :
    flowMatrix m ω (s + t) = flowMatrix m ω s * flowMatrix m ω t := by
  by_cases hω : ω = 0
  · simp [flowMatrix, hω]
  · have hK2 := K_sq m ω hm
    have e1 : (Real.sin (ω * t) / ω) * (Real.sin (ω * s) / ω) * -(ω ^ 2)
        = -(Real.sin (ω * s) * Real.sin (ω * t)) := by
      field_simp
    have key : flowMatrix m ω s * flowMatrix m ω t =
        (Real.cos (ω * s + ω * t)) • (1 : Matrix (Fin 2) (Fin 2) ℝ)
          + (Real.sin (ω * s + ω * t) / ω) • K m ω := by
      simp only [flowMatrix]
      simp only [add_mul, mul_add, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul,
        Matrix.mul_one, smul_smul]
      rw [hK2, smul_smul, e1, Real.cos_add, Real.sin_add]
      module
    rw [key, show ω * s + ω * t = ω * (s + t) from by ring]
    rfl

/-- The flow is a one-parameter group of linear maps. -/
theorem flow_add (hm : m ≠ 0) (hω : ω ≠ 0) (s t : ℝ) :
    flow m ω (s + t) = flow m ω s * flow m ω t := by
  rw [flow_eq m ω hm hω, flow_eq m ω hm hω, flow_eq m ω hm hω, flowMatrix_add m ω hm, map_mul]

end ClassicalMechanics.HarmonicOscillator.OperatorAlgebra
