/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.Unbounded.QuantumMechanics.OperatorAlgebra.Affil.NormalAffiliated
public import PhyslibAlpha.Unbounded.QuantumMechanics.OperatorAlgebra.Calculus.WeakStarCalculus

/-!
# Canonical measurable calculus for normal affiliated objects

`NormalAffiliated.lean` keeps the per-PVM calculus explicit, which is useful when comparing two
different constructions.  The weak-* calculus construction is canonical, however, so ordinary
users should not have to thread a certificate through every bounded functional-calculus call.
This file provides that ergonomic layer while retaining the certificate-taking definitions and
their proofs unchanged.
-/

@[expose] public section

noncomputable section

open scoped ComplexOrder CStarAlgebra Function
open OperatorAlgebra

namespace OperatorAlgebra

variable {A : Type*} [WStarAlgebra A]

namespace NormalAffiliatedObservable

variable (T : NormalAffiliatedObservable A)

/-- The canonical bounded Borel calculus of a normal affiliated observable. -/
noncomputable def canonicalBorelCalculus :
    NormalBorelFunctionalCalculus T.spectralMeasure :=
  NormalBorelFunctionalCalculus.ofNormalPVM T.spectralMeasure

/-- Apply the canonical bounded measurable calculus. -/
noncomputable def canonicalBoundedFC (f : ℝ → ℂ) (hf : Measurable f)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C) : A :=
  T.boundedFC T.canonicalBorelCalculus f hf hfb

/-- The canonical value is independent of the bounded-calculus certificate used to compute it. -/
lemma boundedFC_eq_canonical (C : NormalBorelFunctionalCalculus T.spectralMeasure)
    (f : ℝ → ℂ) (hf : Measurable f) (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C) :
    T.boundedFC C f hf hfb = T.canonicalBoundedFC f hf hfb := by
  exact C.boundedFC_eq_of_same_normalPVM T.canonicalBorelCalculus hf hfb

@[simp]
lemma canonicalBoundedFC_indicator {S : Set ℝ} (hS : MeasurableSet S) :
    T.canonicalBoundedFC (AffiliatedObservable.indicatorFunction S)
      (AffiliatedObservable.indicatorFunction_measurable hS)
      (AffiliatedObservable.indicatorFunction_bounded S) = T.spectralMeasure S := by
  exact T.boundedFC_indicator T.canonicalBorelCalculus hS

lemma canonicalBoundedFC_congr {f g : ℝ → ℂ}
    (hf : Measurable f) (hg : Measurable g)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hgb : ∃ C : ℝ, ∀ x, ‖g x‖ ≤ C)
    (hfg : ∀ x, f x = g x) :
    T.canonicalBoundedFC f hf hfb = T.canonicalBoundedFC g hg hgb := by
  exact T.canonicalBorelCalculus.boundedFC_congr hf hg hfb hgb hfg

lemma canonicalBoundedFC_add {f g : ℝ → ℂ}
    (hf : Measurable f) (hg : Measurable g)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hgb : ∃ C : ℝ, ∀ x, ‖g x‖ ≤ C)
    (hfg : ∃ C : ℝ, ∀ x, ‖f x + g x‖ ≤ C) :
    T.canonicalBoundedFC (f + g) (hf.add hg) hfg =
      T.canonicalBoundedFC f hf hfb + T.canonicalBoundedFC g hg hgb := by
  exact T.canonicalBorelCalculus.boundedFC_add hf hg hfb hgb hfg

lemma canonicalBoundedFC_mul {f g : ℝ → ℂ}
    (hf : Measurable f) (hg : Measurable g)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hgb : ∃ C : ℝ, ∀ x, ‖g x‖ ≤ C)
    (hfg : ∃ C : ℝ, ∀ x, ‖f x * g x‖ ≤ C) :
    T.canonicalBoundedFC (f * g) (hf.mul hg) hfg =
      T.canonicalBoundedFC f hf hfb * T.canonicalBoundedFC g hg hgb := by
  exact T.canonicalBorelCalculus.boundedFC_mul hf hg hfb hgb hfg

lemma canonicalBoundedFC_star {f : ℝ → ℂ}
    (hf : Measurable f) (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hstar : ∃ C : ℝ, ∀ x, ‖star (f x)‖ ≤ C) :
    T.canonicalBoundedFC (fun x => star (f x))
        (continuous_star.measurable.comp hf) hstar =
      star (T.canonicalBoundedFC f hf hfb) := by
  exact T.canonicalBorelCalculus.boundedFC_star hf hfb hstar

/-- The canonical unitary group generated by a real normal affiliated observable. -/
noncomputable def canonicalExpUnitary (t : ℝ) : unitary A :=
  T.expUnitary T.canonicalBorelCalculus t

/-- The canonical exponential is independent of the bounded-calculus certificate. -/
lemma expUnitary_eq_canonical (C : NormalBorelFunctionalCalculus T.spectralMeasure) (t : ℝ) :
    T.expUnitary C t = T.canonicalExpUnitary t := by
  apply Subtype.ext
  exact T.boundedFC_eq_canonical C (AffiliatedObservable.expFunction t)
    (AffiliatedObservable.expFunction_measurable t)
    (AffiliatedObservable.expFunction_bounded t)

@[simp]
lemma canonicalExpUnitary_zero : T.canonicalExpUnitary 0 = 1 := by
  exact T.expUnitary_zero T.canonicalBorelCalculus

lemma canonicalExpUnitary_add (t s : ℝ) :
    T.canonicalExpUnitary (t + s) =
      T.canonicalExpUnitary t * T.canonicalExpUnitary s := by
  exact T.expUnitary_add T.canonicalBorelCalculus t s

/-! The conventional Schrödinger sign is the same canonical group at negative time. -/

/-- The canonical algebra-level unitary `exp (-i t T)`. -/
noncomputable def canonicalNegativeExpUnitary (t : ℝ) : unitary A :=
  T.canonicalExpUnitary (-t)

@[simp]
lemma canonicalNegativeExpUnitary_zero : T.canonicalNegativeExpUnitary 0 = 1 := by
  simpa [canonicalNegativeExpUnitary] using T.canonicalExpUnitary_zero

lemma canonicalNegativeExpUnitary_add (t s : ℝ) :
    T.canonicalNegativeExpUnitary (t + s) =
      T.canonicalNegativeExpUnitary t * T.canonicalNegativeExpUnitary s := by
  change T.canonicalExpUnitary (-(t + s)) =
    T.canonicalExpUnitary (-t) * T.canonicalExpUnitary (-s)
  rw [show -(t + s) = -t + -s by ring]
  exact T.canonicalExpUnitary_add (-t) (-s)

/-- The canonical bounded resolvent of a real normal affiliated observable. -/
noncomputable def canonicalResolvent (z : ℂ) (hz : z.im ≠ 0) : A :=
  T.resolvent T.canonicalBorelCalculus z hz

/-- The canonical resolvent is independent of the bounded-calculus certificate. -/
lemma resolvent_eq_canonical (C : NormalBorelFunctionalCalculus T.spectralMeasure)
    (z : ℂ) (hz : z.im ≠ 0) :
    T.resolvent C z hz = T.canonicalResolvent z hz := by
  exact T.boundedFC_eq_canonical C (AffiliatedObservable.resolventFunction z)
    (AffiliatedObservable.resolventFunction_measurable z)
    (AffiliatedObservable.resolventFunction_bounded z hz)

lemma canonicalResolvent_identity (z w : ℂ) (hz : z.im ≠ 0) (hw : w.im ≠ 0) :
    T.canonicalResolvent z hz - T.canonicalResolvent w hw =
      (z - w) • (T.canonicalResolvent z hz * T.canonicalResolvent w hw) := by
  exact T.resolvent_identity T.canonicalBorelCalculus z w hz hw

end NormalAffiliatedObservable

namespace NormalAffiliatedOperator

variable (T : NormalAffiliatedOperator A)

/-- The canonical bounded Borel calculus of a normal affiliated operator with complex spectrum. -/
noncomputable def canonicalBorelCalculus :
    NormalBorelFunctionalCalculus T.spectralMeasure :=
  NormalBorelFunctionalCalculus.ofNormalPVM T.spectralMeasure

/-- Apply the canonical bounded complex measurable calculus. -/
noncomputable def canonicalBoundedFC (f : ℂ → ℂ) (hf : Measurable f)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C) : A :=
  T.boundedFC T.canonicalBorelCalculus f hf hfb

/-- The canonical complex value is independent of the bounded-calculus certificate used to compute
it. -/
lemma boundedFC_eq_canonical (C : NormalBorelFunctionalCalculus T.spectralMeasure)
    (f : ℂ → ℂ) (hf : Measurable f) (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C) :
    T.boundedFC C f hf hfb = T.canonicalBoundedFC f hf hfb := by
  exact C.boundedFC_eq_of_same_normalPVM T.canonicalBorelCalculus hf hfb

@[simp]
lemma canonicalBoundedFC_indicator {S : Set ℂ} (hS : MeasurableSet S) :
    T.canonicalBoundedFC (normalIndicatorFunction S)
      (normalIndicatorFunction_measurable hS)
      (normalIndicatorFunction_bounded S) = T.spectralMeasure S := by
  exact T.boundedFC_indicator T.canonicalBorelCalculus hS

lemma canonicalBoundedFC_congr {f g : ℂ → ℂ}
    (hf : Measurable f) (hg : Measurable g)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hgb : ∃ C : ℝ, ∀ x, ‖g x‖ ≤ C)
    (hfg : ∀ x, f x = g x) :
    T.canonicalBoundedFC f hf hfb = T.canonicalBoundedFC g hg hgb := by
  exact T.canonicalBorelCalculus.boundedFC_congr hf hg hfb hgb hfg

lemma canonicalBoundedFC_add {f g : ℂ → ℂ}
    (hf : Measurable f) (hg : Measurable g)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hgb : ∃ C : ℝ, ∀ x, ‖g x‖ ≤ C)
    (hfg : ∃ C : ℝ, ∀ x, ‖f x + g x‖ ≤ C) :
    T.canonicalBoundedFC (f + g) (hf.add hg) hfg =
      T.canonicalBoundedFC f hf hfb + T.canonicalBoundedFC g hg hgb := by
  exact T.canonicalBorelCalculus.boundedFC_add hf hg hfb hgb hfg

lemma canonicalBoundedFC_mul {f g : ℂ → ℂ}
    (hf : Measurable f) (hg : Measurable g)
    (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hgb : ∃ C : ℝ, ∀ x, ‖g x‖ ≤ C)
    (hfg : ∃ C : ℝ, ∀ x, ‖f x * g x‖ ≤ C) :
    T.canonicalBoundedFC (f * g) (hf.mul hg) hfg =
      T.canonicalBoundedFC f hf hfb * T.canonicalBoundedFC g hg hgb := by
  exact T.canonicalBorelCalculus.boundedFC_mul hf hg hfb hgb hfg

lemma canonicalBoundedFC_star {f : ℂ → ℂ}
    (hf : Measurable f) (hfb : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C)
    (hstar : ∃ C : ℝ, ∀ x, ‖star (f x)‖ ≤ C) :
    T.canonicalBoundedFC (fun x => star (f x))
        (continuous_star.measurable.comp hf) hstar =
      star (T.canonicalBoundedFC f hf hfb) := by
  exact T.canonicalBorelCalculus.boundedFC_star hf hfb hstar

end NormalAffiliatedOperator

end OperatorAlgebra
