/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Physlib.QuantumMechanics.OperatorAlgebra.Basic
public import Physlib.QuantumMechanics.OperatorAlgebra.State
public import Physlib.QuantumMechanics.PlanckConstant
public import Physlib.Mathematics.OneParameterSubgroups.Unitary

/-!

# Hamiltonian time evolution

The Hamiltonian of a finite-dimensional quantum system is a self-adjoint
operator, hence an observable `A : 𝒪[d]`. It generates the unitary time evolution

`U(t) = exp (-itA)`.

The resulting family of operators forms a norm-continuous unitary one-parameter
group. Conversely, every norm-continuous unitary one-parameter group has a
unique self-adjoint generator.

Thus Hamiltonians and unitary time evolutions are in one-to-one correspondence.
The general operator-theoretic result is provided by
`UnitaryOneParameterGroup.stoneEquiv`; this file gives its interpretation in
terms of observables and Hamiltonian time evolution.

## Main definitions

* `Observable.timeEvolution`: the unitary time evolution generated by an observable.
* `hamiltonianEquiv`: the equivalence between observables and unitary time evolutions.

## TODO

  adding identity to H will not influence adjoint action

-/

@[expose] public section

open OperatorAlgebra Constants

noncomputable section

namespace QuantumMechanics

variable {d : Type*} [Fintype d] [DecidableEq d]

/--
The unitary time evolution generated by the observable `A`.

With the convention used here, the Hamiltonian `A` generates

`U(t) = exp (-itA)`.
-/
def Observable.timeEvolution (A : 𝒪[d]) :
    UnitaryOneParameterGroup 𝓗[d] :=
  UnitaryOneParameterGroup.ofSelfAdjoint A.property

/-- The time evolution generated by `A` is explicitly `exp (-itA)`. -/
@[simp]
lemma Observable.timeEvolution_apply (A : 𝒪[d]) (t : ℝ) :
    timeEvolution A t =
      NormedSpace.exp ((-(t : ℂ) * Complex.I) • (A : 𝒜[d])) :=
  UnitaryOneParameterGroup.ofSelfAdjoint_apply A.property t

/--
Hamiltonians are equivalent to norm-continuous unitary time evolutions.

The forward direction assigns to an observable `A` the one-parameter group
`U(t) = exp (-itA)`. The inverse direction recovers the unique self-adjoint
generator of the group.
-/
noncomputable def hamiltonianEquiv :
    𝒪[d] ≃ UnitaryOneParameterGroup 𝓗[d] :=
  UnitaryOneParameterGroup.stoneEquiv.symm

/-- `hamiltonianEquiv` sends a Hamiltonian to its unitary time evolution. -/
@[simp]
lemma hamiltonianEquiv_apply (A : 𝒪[d]) :
    hamiltonianEquiv A = Observable.timeEvolution A :=
  rfl

/-- The unitary operator implementing the evolution at time `t`. -/
def Observable.timeEvolutionUnitary (A : 𝒪[d]) (t : ℝ) :
    𝒰[d] :=
  ⟨timeEvolution A t, (timeEvolution A).mem_unitary t⟩

@[simp]
lemma Observable.coe_timeEvolutionUnitary (A : 𝒪[d]) (t : ℝ) :
    (timeEvolutionUnitary A t : 𝒜[d]) = timeEvolution A t :=
  rfl


/-!
## Physical time evolution

Physically, a Hamiltonian generates time evolution at the natural energy scale set by `ℏ`:

`U(t) = exp (-itA/ℏ)`.

This is `Observable.timeEvolution` of the ℏ-rescaled generator `((ℏ:ℂ)⁻¹) • A`.
-/

/-- The physical time evolution generated by the observable `A`, at the natural energy scale
`ℏ`: `U(t) = exp (-itA/ℏ)`. -/
def Observable.timeEvolutionℏ (A : 𝒪[d]) :
    UnitaryOneParameterGroup 𝓗[d] :=
  UnitaryOneParameterGroup.ofSelfAdjoint
    (A := ((ℏ : ℂ)⁻¹) • (A : 𝒜[d]))
    ((show IsSelfAdjoint (ℏ : ℂ) by simp [isSelfAdjoint_iff]).inv₀.smul A.property)

/-- The physical time evolution is explicitly `exp (-itA/ℏ)`. -/
@[simp]
lemma Observable.timeEvolutionℏ_apply (A : 𝒪[d]) (t : ℝ) :
    timeEvolutionℏ A t = NormedSpace.exp ((-(t : ℂ) * Complex.I / ℏ) • (A : 𝒜[d])) := by
  rw [timeEvolutionℏ, UnitaryOneParameterGroup.ofSelfAdjoint_apply, smul_smul]
  congr 1

/-- The unitary operator implementing the physical evolution at time `t`. -/
def Observable.timeEvolutionℏUnitary (A : 𝒪[d]) (t : ℝ) :
    𝒰[d] :=
  ⟨timeEvolutionℏ A t, (timeEvolutionℏ A).mem_unitary t⟩

@[simp]
lemma Observable.coe_timeEvolutionℏUnitary (A : 𝒪[d]) (t : ℝ) :
    (timeEvolutionℏUnitary A t : 𝒜[d]) = timeEvolutionℏ A t :=
  rfl


/-!
## Adjoint action on states

Hamiltonian evolution acts on density operators by unitary conjugation with the time-evolution
unitary, in the Heisenberg/Schrödinger sense that `ρ(t) = U(t) ρ U(t)⋆`.
-/

/-- A density operator evolved for time `t` under the Hamiltonian `A`. -/
noncomputable def DensityOperator.evolve (ρ : 𝒟[d]) (A : 𝒪[d]) (t : ℝ) :
    𝒟[d] :=
  ρ.unitaryConjugate (Observable.timeEvolutionℏUnitary A t)

@[simp]
lemma DensityOperator.toState_evolve (ρ : 𝒟[d]) (A : 𝒪[d]) (t : ℝ) :
    (ρ.evolve A t).toState =
      OperatorAlgebra.State.pullback
        (Unitary.automorphism (Observable.timeEvolutionℏUnitary A t)).symm.toStarAlgHom ρ.toState :=
  ρ.toState_unitaryConjugate (Observable.timeEvolutionℏUnitary A t)


end QuantumMechanics
