/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Physlib.QuantumMechanics.Qubit.backup.Unitary
public import Physlib.Mathematics.OperatorAlgebra.Dynamics
public import Mathlib.Analysis.CStarAlgebra.Exponential

/-!

# Hamiltonian evolution and the Bloch equation

Every qubit Hamiltonian is an observable `Hobs`, decomposing (`Qubit.observableEquiv`) as `h₀ • 1
+ σ h`. Its unitary evolution `U(t) = exp(-it Hobs)` is built here from Mathlib's *existing*
abstract exponential-to-unitary map `selfAdjoint.expUnitary` — no Stone/exponential theory is
redeveloped. This traces out exactly the chain the roadmap asks for:

`Hobs = h₀ • 1 + σ h`
  → unitary evolution `U(t)` (`Qubit.unitaryEvolution`, via `selfAdjoint.expUnitary`)
  → inner automorphism `Unitary.automorphism (U t)`, packaged as an
    `OperatorAlgebra.AutomorphismGroup A` (`Qubit.hamiltonianFlow`)
  → `SO(3)` rotation `R (U t)` (`Qubit/Unitary.lean`)
  → Bloch-vector trajectory and its ODE, `dr/dt = 2 h ⨯₃ r`
    (`Qubit.hasDerivAt_blochTrajectory`), where only the traceless part `h` survives — the
    scalar part `h₀ • 1` commutes with everything and drops out of Heisenberg evolution.

-/

@[expose] public section

open scoped ComplexOrder CStarAlgebra Matrix
open Module OperatorAlgebra

namespace Qubit

variable {A : Type*} [OperatorAlgebra A] [QubitAlgebra A]

/-- The unitary time-evolution operator generated by a Hamiltonian observable, in the convention
`U(t) = exp(-it Hobs)`. Built directly from Mathlib's `selfAdjoint.expUnitary`. -/
noncomputable def unitaryEvolution (Hobs : Observable A) (t : ℝ) : Unitary A :=
  selfAdjoint.expUnitary (t • Hobs)

omit [QubitAlgebra A] in
/-- At time `0`, nothing has happened. -/
lemma unitaryEvolution_zero (Hobs : Observable A) : unitaryEvolution Hobs 0 = 1 := by
  rw [unitaryEvolution, zero_smul, selfAdjoint.expUnitary_zero]

omit [QubitAlgebra A] in
/-- The group law: `t • Hobs` and `s • Hobs` always commute (same underlying element), so
`selfAdjoint.expUnitary` turns addition into multiplication (`Commute.expUnitary_add`). -/
lemma unitaryEvolution_add (Hobs : Observable A) (s t : ℝ) :
    unitaryEvolution Hobs (s + t) = unitaryEvolution Hobs s * unitaryEvolution Hobs t := by
  rw [unitaryEvolution, unitaryEvolution, unitaryEvolution, add_smul]
  exact Commute.expUnitary_add
    (((Commute.refl (Hobs : A)).smul_left s).smul_right t)

/-- Hamiltonian evolution as a genuine reversible dynamics driver
(`OperatorAlgebra.AutomorphismGroup`). -/
noncomputable def hamiltonianFlow (Hobs : Observable A) : AutomorphismGroup A where
  toFun t := Unitary.automorphism (unitaryEvolution Hobs t)
  map_zero_apply a := by rw [unitaryEvolution_zero]; simp
  map_add_apply s t a := by
    rw [unitaryEvolution_add]
    simp only [Unitary.automorphism_apply, MulMemClass.coe_mul, star_mul]
    noncomm_ring

/-- The Bloch-vector trajectory of a fixed Pauli vector `v`, Heisenberg-evolving under `Hobs`.
Tagged `sorryful`: it is built from `Qubit.R`, itself not yet constructed. -/
@[sorryful]
noncomputable def blochTrajectory (Hobs : Observable A) (v : Fin 3 → ℝ) (t : ℝ) : Fin 3 → ℝ :=
  R (unitaryEvolution Hobs t) v

/-- The Bloch equation: `dr/dt = 2 h ⨯₃ r`, where `h` is the *traceless* part of the Hamiltonian
(`Qubit.observableEquiv Hobs`'s second component) — the scalar part commutes with everything and
never appears. Equivalently, finite-time evolution is a rotation, `r(t) = R (U t) v`. -/
@[sorryful]
lemma hasDerivAt_blochTrajectory (Hobs : Observable A) (v : Fin 3 → ℝ) (t : ℝ) :
    HasDerivAt (blochTrajectory Hobs v)
      ((2 : ℝ) • ((observableEquiv Hobs).2 ⨯₃ blochTrajectory Hobs v t)) t :=
  sorry

TODO "Prove `Qubit.hasDerivAt_blochTrajectory`. First show the scalar part drops out: with
  `Hobs = h₀ • 1 + σ h` (`Qubit.observableEquiv`), `t • Hobs = (t * h₀) • 1 + σ (t • h)`, and
  `selfAdjoint.expUnitary` of a sum of *commuting* self-adjoint elements factors
  (`Commute.expUnitary`, `1` commutes with everything), with the `(t * h₀) • 1` factor
  contributing a unimodular scalar that cancels under conjugation
  (`OperatorAlgebra.Unitary.automorphism_apply`, `c * a * star c = a` for `c` a scalar unitary).
  So `Qubit.R (unitaryEvolution Hobs t) = Qubit.R (unitaryEvolution (⟨σ h, isSelfAdjoint_σ h⟩)
  t)`, i.e. only `h` matters. Then differentiate `t ↦ Qubit.coe_R (unitaryEvolution (σ-part) t)
  v`, i.e. `t ↦ exp(-it σ h) σ(v) exp(it σ h) = σ (blochTrajectory Hobs v t)`, at `t`: the
  derivative of the left side is `-i [σ h, exp(-it σ h) σ(v) exp(it σ h)] = -i [σ h, σ (r t)]`,
  and `Qubit.σ_commutator` turns `-i [σ h, σ (r t)] = -i (2i • σ (h ⨯₃ r t)) = 2 • σ (h ⨯₃ r t)`,
  matching `σ` of the claimed derivative via injectivity of `σ`."

end Qubit
