/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Physlib.Mathematics.OneParameterSubgroups.Basic
public import Physlib.QuantumMechanics.PlanckConstant

/-!

# Unitary time evolution from bounded Hamiltonians

## i. Overview

A time-independent bounded Hamiltonian `H` evolves a quantum state by
`U(t) = exp (-itH/ℏ)`. This file proves that norm-continuous unitary time evolutions are in
bijection with bounded self-adjoint Hamiltonians.

For finite-dimensional systems every Hamiltonian is bounded, so this gives the finite-dimensional
form of Stone's theorem used by `FiniteTarget` and quantum-information models. Physlib's general
`QuantumSystem` also permits unbounded Hamiltonians; extending this result to that setting requires
spectral theory and strong operator continuity that are not yet available.

## ii. Key results

* `QuantumMechanics.UnitaryTimeEvolution.ofHamiltonian`: The unitary time evolution
    `U(t) = exp (-itH/ℏ)` generated by a bounded self-adjoint Hamiltonian.
* `QuantumMechanics.UnitaryTimeEvolution.existsUnique_hamiltonian`: Every unitary time evolution
    has a unique bounded self-adjoint Hamiltonian.
* `QuantumMechanics.UnitaryTimeEvolution.stoneEquiv`: The correspondence as an equivalence.

## iii. References

* M. H. Stone, *Linear Transformations in Hilbert Space III. Operational Methods and Group Theory*,
  Proc. Natl. Acad. Sci. 18 (1932), 172-175.

-/

@[expose] public section

open Constants

noncomputable section

namespace QuantumMechanics

/-- A continuous unitary time evolution on a complex Hilbert space. -/
abbrev UnitaryTimeEvolution (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] :=
  ContinuousMonoidHom (Multiplicative ℝ) (unitary (H →L[ℂ] H))

namespace UnitaryTimeEvolution

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

omit [CompleteSpace H] in
lemma real_smul_operator_eq_complex_smul (t : ℝ) (A : H →L[ℂ] H) :
    t • A = (t : ℂ) • A := by
  ext x
  rfl

/-- The operator implementing the time evolution at time `t`. -/
def value (U : UnitaryTimeEvolution H) (t : ℝ) : H →L[ℂ] H := U (.ofAdd t)

@[simp] lemma value_zero (U : UnitaryTimeEvolution H) : value U 0 = 1 := by
  simp [value]

@[simp] lemma value_add (U : UnitaryTimeEvolution H) (s t : ℝ) :
    value U (s + t) = value U s * value U t := by
  exact congrArg Subtype.val (map_mul U (.ofAdd s) (.ofAdd t))

lemma star_value_neg (U : UnitaryTimeEvolution H) (t : ℝ) :
    star (value U (-t)) = value U t := by
  exact left_inv_eq_right_inv (U (.ofAdd (-t))).property.1
    (by
      change value U (-t) * value U t = 1
      rw [← value_add, neg_add_cancel, value_zero])

lemma isSelfAdjoint_I_smul {A : H →L[ℂ] H} (hA : star A = -A) :
    IsSelfAdjoint (Complex.I • A) := by
  rw [isSelfAdjoint_iff, star_smul, Complex.star_def, Complex.conj_I, hA]
  module

/-- A unitary time evolution has a unique bounded self-adjoint Hamiltonian `H`
satisfying `U(t) = exp (-itH/ℏ)`. -/
lemma existsUnique_hamiltonian (U : UnitaryTimeEvolution H) :
    ∃! hamiltonian : H →L[ℂ] H, IsSelfAdjoint hamiltonian ∧
      ∀ t : ℝ, value U t =
        NormedSpace.exp ((-(t : ℂ) * Complex.I / ℏ) • hamiltonian) := by
  obtain ⟨A, hA, hA_unique⟩ := OneParameterSubgroup.existsUnique_generator_of_unitary U
  have hA' (t : ℝ) : value U t = NormedSpace.exp ((t : ℂ) • A) := by
    change (U (.ofAdd t) : H →L[ℂ] H) = _
    rw [← real_smul_operator_eq_complex_smul]
    exact hA t
  have hAstar : star A = -A := by
    have hnegstar : ∀ t : ℝ, (U (.ofAdd t) : H →L[ℂ] H) =
        NormedSpace.exp ((t : ℂ) • (-star A)) := by
      intro t
      calc
        (U (.ofAdd t) : H →L[ℂ] H) = value U t := rfl
        _ = star (value U (-t)) := (U.star_value_neg t).symm
        _ = star (NormedSpace.exp (((-t : ℝ) : ℂ) • A)) := by rw [hA' (-t)]
        _ = NormedSpace.exp (star (((-t : ℝ) : ℂ) • A)) := NormedSpace.star_exp _
        _ = NormedSpace.exp ((t : ℂ) • (-star A)) := by
          congr 1
          simp [star_smul]
    have hgen : -star A = A := hA_unique (-star A) fun t => by
      rw [real_smul_operator_eq_complex_smul]
      exact hnegstar t
    simpa using congrArg Neg.neg hgen
  let K := Complex.I • A
  have hK : IsSelfAdjoint K ∧
      ∀ t : ℝ, value U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • K) := by
    refine ⟨isSelfAdjoint_I_smul hAstar, fun t => ?_⟩
    rw [hA' t]
    dsimp [K]
    rw [smul_smul]
    congr 1
    rw [mul_assoc, Complex.I_mul_I]
    simp
  have hK_unique : ∀ K' : H →L[ℂ] H, IsSelfAdjoint K' ∧
      (∀ t : ℝ, value U t = NormedSpace.exp ((-(t : ℂ) * Complex.I) • K')) → K' = K := by
    intro K' hK'
    have hKrep : ∀ t : ℝ, (U (.ofAdd t) : H →L[ℂ] H) =
        NormedSpace.exp (t • ((-Complex.I) • K')) := by
      intro t
      change value U t =
        NormedSpace.exp ((t : ℂ) • ((-Complex.I) • K'))
      rw [hK'.2 t]
      congr 1
      rw [smul_smul]
      apply congrArg (fun z : ℂ => z • K')
      ring
    have hKA : (-Complex.I) • K' = A := hA_unique ((-Complex.I) • K') hKrep
    calc
      K' = Complex.I • ((-Complex.I) • K') := by rw [smul_smul]; simp
      _ = Complex.I • A := by rw [hKA]
      _ = K := rfl
  let hamiltonian : H →L[ℂ] H := (ℏ : ℂ) • K
  have hℏself : IsSelfAdjoint (ℏ : ℂ) := by
    rw [isSelfAdjoint_iff, Complex.star_def, Complex.conj_ofReal]
  have hℏinvself : IsSelfAdjoint (ℏ : ℂ)⁻¹ := hℏself.inv₀
  refine ⟨hamiltonian, ⟨hℏself.smul hK.1, ?_⟩, ?_⟩
  · intro t
    rw [hA' t]
    apply congrArg NormedSpace.exp
    dsimp [hamiltonian, K]
    have hc : (-(t : ℂ) * Complex.I / ℏ) * ℏ * Complex.I = (t : ℂ) := by
      field_simp [Constants.ℏ_ne_zero]
      rw [Complex.I_sq]
      ring
    calc
      (t : ℂ) • A = ((-(t : ℂ) * Complex.I / ℏ) * ℏ * Complex.I) • A := by rw [hc]
      _ = (-(t : ℂ) * Complex.I / ℏ) • ((ℏ : ℂ) • (Complex.I • A)) := by
        rw [smul_smul, smul_smul]
  · intro hamiltonian' hHamiltonian'
    have hrep : ∀ t : ℝ, value U t =
        NormedSpace.exp ((-(t : ℂ) * Complex.I) • ((ℏ : ℂ)⁻¹ • hamiltonian')) := by
      intro t
      rw [hHamiltonian'.2 t]
      congr 1
      rw [smul_smul]
      apply congrArg (fun z : ℂ => z • hamiltonian')
      field_simp [Constants.ℏ_ne_zero]
    have hHamiltonianK : (ℏ : ℂ)⁻¹ • hamiltonian' = K :=
      hK_unique ((ℏ : ℂ)⁻¹ • hamiltonian') ⟨hℏinvself.smul hHamiltonian'.1, hrep⟩
    calc
      hamiltonian' = (ℏ : ℂ) • ((ℏ : ℂ)⁻¹ • hamiltonian') := by
        rw [smul_smul]
        simp [Constants.ℏ_ne_zero]
      _ = (ℏ : ℂ) • K := by rw [hHamiltonianK]
      _ = hamiltonian := rfl

/-- The unitary time evolution generated by a bounded self-adjoint Hamiltonian `H`, with
`U(t) = exp (-itH/ℏ)`. -/
def ofHamiltonian {hamiltonian : H →L[ℂ] H} (hHamiltonian : IsSelfAdjoint hamiltonian) :
    UnitaryTimeEvolution H := by
  letI : NormedAlgebra ℚ (H →L[ℂ] H) := .restrictScalars ℚ ℂ (H →L[ℂ] H)
  let A : H →L[ℂ] H := (-Complex.I / ℏ) • hamiltonian
  have hA : star A = -A := by
    dsimp [A]
    rw [star_smul, Complex.star_def, map_div₀, map_neg, Complex.conj_I,
      Complex.conj_ofReal, hHamiltonian.star_eq]
    module
  let E : Multiplicative ℝ →* H →L[ℂ] H := {
    toFun t := NormedSpace.exp (((Multiplicative.toAdd t : ℝ) : ℂ) • A)
    map_one' := by simp
    map_mul' := fun s t => by
      have hcomm : Commute (((Multiplicative.toAdd s : ℝ) : ℂ) • A)
          (((Multiplicative.toAdd t : ℝ) : ℂ) • A) :=
        ((Commute.refl A).smul_left _).smul_right _
      change NormedSpace.exp (((Multiplicative.toAdd (s * t) : ℝ) : ℂ) • A) =
        NormedSpace.exp (((Multiplicative.toAdd s : ℝ) : ℂ) • A) *
          NormedSpace.exp (((Multiplicative.toAdd t : ℝ) : ℂ) • A)
      rw [← NormedSpace.exp_add_of_commute hcomm, toAdd_mul]
      push_cast
      rw [add_smul] }
  exact {
    toMonoidHom := E.codRestrict (unitary (H →L[ℂ] H)) fun t => by
      apply NormedSpace.exp_mem_unitary_of_mem_skewAdjoint
      rw [skewAdjoint.mem_iff, star_smul, Complex.star_def, Complex.conj_ofReal, hA]
      module
    continuous_toFun := Continuous.subtype_mk (by
      change Continuous
        (fun t : Multiplicative ℝ => NormedSpace.exp (((Multiplicative.toAdd t : ℝ) : ℂ) • A))
      fun_prop) _ }

@[simp] lemma value_ofHamiltonian {hamiltonian : H →L[ℂ] H}
    (hHamiltonian : IsSelfAdjoint hamiltonian) (t : ℝ) :
    value (ofHamiltonian hHamiltonian) t =
      NormedSpace.exp ((-(t : ℂ) * Complex.I / ℏ) • hamiltonian) := by
  simp only [ofHamiltonian, value]
  change NormedSpace.exp ((t : ℂ) • ((-Complex.I / ℏ) • hamiltonian)) = _
  rw [smul_smul]
  congr 1
  field_simp [Constants.ℏ_ne_zero]

/-- Stone's correspondence for bounded Hamiltonians and unitary time evolution,
using the convention `U(t) = exp (-itH/ℏ)`. -/
noncomputable def stoneEquiv :
    UnitaryTimeEvolution H ≃ {hamiltonian : H →L[ℂ] H // IsSelfAdjoint hamiltonian} where
  toFun U := ⟨U.existsUnique_hamiltonian.choose, U.existsUnique_hamiltonian.choose_spec.1.1⟩
  invFun hamiltonian := ofHamiltonian hamiltonian.2
  left_inv U := by
    apply DFunLike.ext
    intro t
    induction t using Multiplicative.rec with
    | ofAdd a =>
      apply Subtype.ext
      change value (ofHamiltonian _) a = value U a
      rw [value_ofHamiltonian, ← U.existsUnique_hamiltonian.choose_spec.1.2]
  right_inv hamiltonian := by
    apply Subtype.ext
    exact ((ofHamiltonian hamiltonian.2).existsUnique_hamiltonian.choose_spec.2 hamiltonian.1
      ⟨hamiltonian.2, value_ofHamiltonian hamiltonian.2⟩).symm

end UnitaryTimeEvolution

end QuantumMechanics
