/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.Unbounded.QuantumMechanics.OperatorAlgebra.Dynamics.Automorphism

/-!

# Hamiltonian dynamics

A bounded Hamiltonian `H` determines

    U_H(t) = exp(-itH/ℏ)

and the automorphism flow

    αₜ(a) = U_H(t) a U_H(t)⋆.

This is the special case of `UnitaryOneParameterGroup.toAutomorphism`/`hasDerivAt_toAutomorphism`/
`toAutomorphism_unique` (`Dynamics.Automorphism`) where the generating unitary group is
`unitaryEvolution ℏ H`, so the flow is the unique solution of

    dαₜ(a)/dt = -(i/ℏ) [H, αₜ(a)],
    α₀ = id.

Shifting `H` by a real multiple of the identity changes `U_H(t)` only by a scalar phase (it adds a
central term to the generator, which the Heisenberg equation's commutator kills) and therefore
leaves the automorphism flow unchanged. For `B(𝓗)` this is the only ambiguity.

-/

@[expose] public section

namespace OperatorAlgebra

open scoped ComplexOrder CStarAlgebra

variable {𝓗 : Type*} [NormedAddCommGroup 𝓗] [InnerProductSpace ℂ 𝓗] [CompleteSpace 𝓗]

/-- Needed to invoke `NormedSpace.map_exp` (which requires `Algebra ℚ` on the target algebra) at
`B(𝓗)`; obtained by restricting the ambient `NormedAlgebra ℂ (B(𝓗))` along `ℚ ⊆ ℂ`. -/
noncomputable local instance : NormedAlgebra ℚ (B(𝓗)) :=
  .restrictScalars ℚ ℂ (B(𝓗))

namespace UnitaryOneParameterGroup

/-! ## Unitary evolution -/

/-- The unitary evolution `U_H(t) = exp(-itH/ℏ)` generated by `H`, obtained from Stone's theorem
(`stoneEquiv`) applied to the self-adjoint generator `ℏ⁻¹ • H`. -/
noncomputable def unitaryEvolution
    (ℏ : ℝ) (H : Observable (B(𝓗))) :
    UnitaryOneParameterGroup 𝓗 :=
  (UnitaryOneParameterGroup.stoneEquiv).symm (ℏ⁻¹ • H)

/-- The generator of `unitaryEvolution` is `ℏ⁻¹ • H`, by definition of `stoneEquiv`. -/
@[simp]
lemma unitaryEvolution_generator
    (ℏ : ℝ) (H : Observable (B(𝓗))) :
    (unitaryEvolution ℏ H).generator =
      (ℏ⁻¹ : ℝ) • (H : B(𝓗)) := by
  simp [unitaryEvolution, UnitaryOneParameterGroup.stoneEquiv]

/-- The closed form `U_H(t) = exp(-itH/ℏ)`, unfolding a one-parameter group to its generator's
exponential (`apply_eq_exp_generator`) and substituting the generator above. -/
lemma unitaryEvolution_apply
    (ℏ : ℝ) (H : Observable (B(𝓗))) (t : ℝ) :
    unitaryEvolution ℏ H t =
      NormedSpace.exp
        ((-(t : ℂ) * Complex.I) •
          ((ℏ⁻¹ : ℝ) • (H : B(𝓗)))) := by
  rw [UnitaryOneParameterGroup.apply_eq_exp_generator]
  rw [unitaryEvolution_generator]

/-! ## Hamiltonian flow -/

/-- The automorphism flow induced by the unitary evolution generated by `H`. -/
noncomputable def hamiltonianFlow
    (ℏ : ℝ) (H : Observable (B(𝓗))) :
    AutomorphismGroup (B(𝓗)) :=
  toAutomorphism (unitaryEvolution ℏ H)

/-- Unfolds `hamiltonianFlow` to the concrete conjugation formula `a ↦ U(t) a U(t)⋆`. -/
@[simp]
lemma hamiltonianFlow_apply
    (ℏ : ℝ) (H : Observable (B(𝓗))) (t : ℝ) (a : B(𝓗)) :
    (hamiltonianFlow ℏ H).toFun t a =
      unitaryEvolution ℏ H t * a * star (unitaryEvolution ℏ H t) := by
  simp [hamiltonianFlow]

/-! ## Equivariance under star automorphisms

Changing the representation of the algebra by a ⋆-automorphism `β` conjugates the flow generated
by `β(H)` by `β`: `α_t^(β(H)) = β ∘ α_t^H ∘ β⁻¹`. Physically, this says the Hamiltonian flow does
not care which unitarily-equivalent copy of `B(𝓗)` the Hamiltonian happens to be written in. -/

/-- Conjugating the generating unitary by `β` amounts to applying `β` pointwise: `β` is a
continuous ring homomorphism (every ⋆-algebra homomorphism between C⋆-algebras is norm
contractive, `NonUnitalStarAlgHom.isometry`), so it commutes with `NormedSpace.exp`
(`NormedSpace.map_exp`), and it is `ℂ`-linear, so it commutes with the scalar exponent. -/
lemma unitaryEvolution_map (ℏ : ℝ) (β : B(𝓗) ≃⋆ₐ[ℂ] B(𝓗)) (H : Observable (B(𝓗))) (t : ℝ) :
    unitaryEvolution ℏ (β.observable H) t = β (unitaryEvolution ℏ H t) := by
  have hcont : Continuous β := (NonUnitalStarAlgHom.isometry β β.injective).continuous
  -- `β` is only registered as `ℂ`-linear, so rewrite the inner real scalar `ℏ⁻¹ • _` as a
  -- complex one before pushing `β` through it (`map_smul` needs matching scalar types).
  have hreal : ∀ x : B(𝓗), (ℏ⁻¹ : ℝ) • x = ((ℏ⁻¹ : ℝ) : ℂ) • x := fun x => by
    have h' : ((ℏ⁻¹ : ℝ) : ℂ) = algebraMap ℝ ℂ (ℏ⁻¹ : ℝ) := by norm_cast
    rw [h', IsScalarTower.algebraMap_smul]
  rw [unitaryEvolution_apply, unitaryEvolution_apply, hreal, hreal,
    NormedSpace.map_exp β hcont, map_smul, map_smul, StarAlgEquiv.observable_coe]

/-- The Hamiltonian flow is equivariant under ⋆-automorphism conjugation: the flow generated by
`β(H)` is the flow generated by `H`, viewed through the change of coordinates `β`
(`AutomorphismGroup.conj`). Proved algebraically from `unitaryEvolution_map`, with no
differentiation needed: unfold both flows to the `U(t) a U(t)⋆` level, push `β` through the
unitary via `unitaryEvolution_map`, then push it back out over the product via `map_mul`/
`map_star`. -/
lemma hamiltonianFlow_map (ℏ : ℝ) (β : B(𝓗) ≃⋆ₐ[ℂ] B(𝓗)) (H : Observable (B(𝓗))) :
    hamiltonianFlow ℏ (β.observable H) = (hamiltonianFlow ℏ H).conj β := by
  apply AutomorphismGroup.ext
  intro t a
  rw [AutomorphismGroup.conj_apply, hamiltonianFlow_apply, hamiltonianFlow_apply,
    unitaryEvolution_map, map_mul, map_mul, map_star, β.apply_symm_apply]

/-- The unitary specialization of `hamiltonianFlow_map`: if `K = V H V⋆` for a unitary `V`, the
flow generated by `K` is the flow generated by `H`, conjugated by `Ad_V`. An instance of the
general theorem at `β = Unitary.conjStarAlgAut ℂ (B(𝓗)) V`, not a re-proof. -/
lemma hamiltonianFlow_conj_unitary (ℏ : ℝ) (V : unitary (B(𝓗))) (H : Observable (B(𝓗))) :
    hamiltonianFlow ℏ ((Unitary.conjStarAlgAut ℂ (B(𝓗)) V).observable H) =
      (hamiltonianFlow ℏ H).conj (Unitary.conjStarAlgAut ℂ (B(𝓗)) V) :=
  hamiltonianFlow_map ℏ (Unitary.conjStarAlgAut ℂ (B(𝓗)) V) H

/-! ## Differential characterization

Every fact here is a one-line specialization of the generic `UnitaryOneParameterGroup` API
(`Dynamics.Automorphism`) to `U = unitaryEvolution ℏ H`; the only Hamiltonian-specific content is
relating `U`'s abstract generator to the closed form `(i/ℏ) H`. -/

/-- The real-scalar structure `B(𝓗)` needs to state `HasDerivAt` over `ℝ` (the Heisenberg
equation differentiates in the real time parameter `t`), obtained by restricting the ambient
`ℂ`-algebra structure along `ℝ ⊆ ℂ`. -/
noncomputable local instance : NormedAlgebra ℝ (B(𝓗)) :=
  { NormedSpace.complexToReal, NormedAlgebra.complexToReal with }

/-- The scaled Hamiltonian `(i/ℏ) H`, the generator appearing on the right of the Heisenberg
equation `dαₜ(a)/dt = -(i/ℏ)[H, αₜ(a)]`. Naming it once here avoids re-deriving its basic
properties (below) separately in every lemma that needs them. -/
noncomputable def G (ℏ : ℝ) (H : Observable (B(𝓗))) : B(𝓗) :=
  (Complex.I / (ℏ : ℂ)) • (H : B(𝓗))

/-- `G` is `i` times the abstract generator of `unitaryEvolution`, up to the real/complex scalar
identification and the algebraic rearrangement `i • (ℏ⁻¹ • H) = (i/ℏ) • H`. -/
private lemma smul_I_generator (ℏ : ℝ) (H : Observable (B(𝓗))) :
    Complex.I • (unitaryEvolution ℏ H).generator = G ℏ H := by
  have h : (ℏ⁻¹ : ℝ) • (H : B(𝓗)) = ((ℏ⁻¹ : ℝ) : ℂ) • (H : B(𝓗)) := by
    have h' : ((ℏ⁻¹ : ℝ) : ℂ) = algebraMap ℝ ℂ (ℏ⁻¹ : ℝ) := by norm_cast
    rw [h', IsScalarTower.algebraMap_smul]
  rw [unitaryEvolution_generator, h, smul_smul]
  congr 1
  simp [div_eq_mul_inv]

/-- The Hamiltonian flow satisfies the Heisenberg equation of motion `d/dt αₜ(a) = ⁅αₜ(a), G⁆`, by
specializing `hasDerivAt_toAutomorphism`. -/
lemma hasDerivAt_hamiltonianFlow (ℏ : ℝ) (H : Observable (B(𝓗))) (a : B(𝓗)) (t : ℝ) :
    HasDerivAt (fun t : ℝ => (hamiltonianFlow ℏ H).toFun t a)
      ⁅(hamiltonianFlow ℏ H).toFun t a, G ℏ H⁆ t := by
  rw [← smul_I_generator]
  exact hasDerivAt_toAutomorphism (unitaryEvolution ℏ H) a t

/-- The Hamiltonian flow is the unique solution of the corresponding initial-value problem, by
specializing `toAutomorphism_unique`. -/
lemma hamiltonianFlow_unique (ℏ : ℝ) (H : Observable (B(𝓗)))
    (α : ℝ → B(𝓗) → B(𝓗)) (hα0 : α 0 = id)
    (hα : ∀ a t, HasDerivAt (fun s : ℝ => α s a) ⁅α t a, G ℏ H⁆ t) :
    α = fun t a => (hamiltonianFlow ℏ H).toFun t a := by
  apply toAutomorphism_unique (unitaryEvolution ℏ H) α hα0
  intro a t
  rw [smul_I_generator]
  exact hα a t

/-! ## Hamiltonians modulo scalar shifts -/

/-- Shifting `H` by `c • 1` shifts `G` by a central (scalar-multiple-of-`1`) term. -/
private lemma G_add_smul_one (ℏ : ℝ) (H : Observable (B(𝓗))) (c : ℝ) :
    G ℏ (H + c • 1) = G ℏ H + ((Complex.I / (ℏ : ℂ)) * (c : ℂ)) • (1 : B(𝓗)) := by
  have hc : (c : ℝ) • (1 : B(𝓗)) = (c : ℂ) • (1 : B(𝓗)) := by
    have h' : (c : ℂ) = algebraMap ℝ ℂ c := by norm_cast
    rw [h', IsScalarTower.algebraMap_smul]
  show (Complex.I / (ℏ : ℂ)) • ((H : B(𝓗)) + c • (1 : B(𝓗))) =
    (Complex.I / (ℏ : ℂ)) • (H : B(𝓗)) + ((Complex.I / (ℏ : ℂ)) * (c : ℂ)) • (1 : B(𝓗))
  rw [smul_add, hc, smul_smul]

/-- A central element (a scalar multiple of `1`) brackets to zero with anything. -/
private lemma central_cancel (z : ℂ) (x : B(𝓗)) :
    ⁅x, z • (1 : B(𝓗))⁆ = 0 := by
  simp [LieRing.of_associative_ring_bracket]

/-- The bracket distributes over addition in its second argument (the ring-commutator bracket is
bi-additive). -/
private lemma lie_add' (x m n : B(𝓗)) : ⁅x, m + n⁆ = ⁅x, m⁆ + ⁅x, n⁆ := by
  simp only [LieRing.of_associative_ring_bracket]
  noncomm_ring

/-- Scalar shifts do not change the automorphism flow: `H` and `H + c • 1` generate the same
Heisenberg equation, since the extra central term `G ℏ (H + c • 1) - G ℏ H` brackets to zero
(`central_cancel`, via `lie_add'`); uniqueness (`hamiltonianFlow_unique`) then forces the flows to
agree. -/
lemma hamiltonianFlow_add_smul_one
    (ℏ : ℝ) (H : Observable (B(𝓗))) (c : ℝ) :
    hamiltonianFlow ℏ (H + c • 1) =
      hamiltonianFlow ℏ H := by
  apply AutomorphismGroup.ext
  intro t a
  have huniq := hamiltonianFlow_unique ℏ H
    (fun t a => (hamiltonianFlow ℏ (H + c • 1)).toFun t a) (by ext a; simp) ?_
  · exact congrFun (congrFun huniq t) a
  · intro a t
    have hd := hasDerivAt_hamiltonianFlow ℏ (H + c • 1) a t
    rwa [G_add_smul_one, lie_add', central_cancel, add_zero] at hd

/-- Hamiltonians differing by a real scalar multiple of the identity generate the same flow. -/
lemma hamiltonianFlow_eq_of_eq_add_smul_one
    (ℏ : ℝ) (H K : Observable (B(𝓗))) (c : ℝ)
    (h : H = K + c • 1) :
    hamiltonianFlow ℏ H = hamiltonianFlow ℏ K := by
  rw [h]
  exact hamiltonianFlow_add_smul_one ℏ K c

/-! ## Classification up to star-automorphism conjugation

Combining equivariance (`hamiltonianFlow_map`) with scalar-shift invariance
(`hamiltonianFlow_add_smul_one`) gives the full classification of when two Hamiltonians generate
conjugate flows: `K` generates the `β`-conjugate of `H`'s flow exactly when `K = β(H) + c • 1` for
some real `c`. The converse direction needs a genuine differential argument
(`hamiltonianFlow_eq_iff`, below), reusing the same central-element technique
`Algebra.IsCentral` provides for `Aut⋆(B(𝓗))`'s kernel elsewhere in this development. -/

/-- If `K = β(H) + c • 1`, the flow generated by `K` is `H`'s flow viewed through `β`. Chains
`hamiltonianFlow_add_smul_one` (scalar shifts don't change the flow) with `hamiltonianFlow_map`
(⋆-automorphisms conjugate the flow). -/
lemma hamiltonianFlow_map_add_smul_one (ℏ : ℝ) (β : B(𝓗) ≃⋆ₐ[ℂ] B(𝓗))
    (H K : Observable (B(𝓗))) (c : ℝ) (h : K = β.observable H + c • 1) :
    hamiltonianFlow ℏ K = (hamiltonianFlow ℏ H).conj β := by
  rw [h, hamiltonianFlow_add_smul_one, hamiltonianFlow_map]

/-- Two Hamiltonians generate the same flow (at a fixed representation, `β = id`) exactly when
they differ by a real scalar multiple of the identity: the converse to
`hamiltonianFlow_add_smul_one`/`hamiltonianFlow_eq_of_eq_add_smul_one`.

Forward direction: if the flows agree as functions of `(t, a)`, so do their derivatives at
`t = 0`; by the Heisenberg equation (`hasDerivAt_hamiltonianFlow`) this forces `⁅a, G ℏ H⁆ =
⁅a, G ℏ K⁆` for every `a`, i.e. `G ℏ H - G ℏ K` commutes with everything, i.e. it is central.
Since `B(𝓗)` is a central `ℂ`-algebra (`Algebra.IsCentral`, from `SeparatingDual`), a central
element is a scalar multiple of `1`; self-adjointness of `H - K` then forces that scalar to be
real. -/
theorem hamiltonianFlow_eq_iff (ℏ : ℝ) (hℏ : ℏ ≠ 0) [Nontrivial (B(𝓗))]
    (H K : Observable (B(𝓗))) :
    hamiltonianFlow ℏ H = hamiltonianFlow ℏ K ↔ ∃ c : ℝ, H = K + c • 1 := by
  constructor
  · intro heq
    have hcomm : ∀ a : B(𝓗), a * (G ℏ H - G ℏ K) = (G ℏ H - G ℏ K) * a := by
      intro a
      have hH := hasDerivAt_hamiltonianFlow ℏ H a 0
      have hK := hasDerivAt_hamiltonianFlow ℏ K a 0
      rw [(hamiltonianFlow ℏ H).map_zero_apply a] at hH
      rw [(hamiltonianFlow ℏ K).map_zero_apply a] at hK
      rw [heq] at hH
      have hbracket := hH.unique hK
      simp only [LieRing.of_associative_ring_bracket] at hbracket
      have hexpand : a * (G ℏ H - G ℏ K) - (G ℏ H - G ℏ K) * a
          = (a * G ℏ H - G ℏ H * a) - (a * G ℏ K - G ℏ K * a) := by noncomm_ring
      rw [hbracket, sub_self] at hexpand
      exact sub_eq_zero.mp hexpand
    have hcentral : G ℏ H - G ℏ K ∈ Subalgebra.center ℂ (B(𝓗)) :=
      Subalgebra.mem_center_iff.mpr hcomm
    obtain ⟨z, hz⟩ := (Algebra.IsCentral.mem_center_iff (K := ℂ)).mp hcentral
    rw [Algebra.algebraMap_eq_smul_one] at hz
    have hGdiff : G ℏ H - G ℏ K = (Complex.I / (ℏ : ℂ)) • ((H : B(𝓗)) - (K : B(𝓗))) := by
      simp only [G, smul_sub]
    have ha : (Complex.I / (ℏ : ℂ)) ≠ 0 :=
      div_ne_zero Complex.I_ne_zero (by exact_mod_cast hℏ)
    have heq2 : (Complex.I / (ℏ : ℂ)) • ((H : B(𝓗)) - (K : B(𝓗))) = z • (1 : B(𝓗)) :=
      hGdiff.symm.trans hz
    have hHK : (H : B(𝓗)) - (K : B(𝓗))
        = ((Complex.I / (ℏ : ℂ))⁻¹ * z) • (1 : B(𝓗)) := by
      rw [← smul_smul]
      exact (eq_inv_smul_iff₀ ha).mpr heq2
    set w : ℂ := (Complex.I / (ℏ : ℂ))⁻¹ * z with hw
    have hselfadjoint : IsSelfAdjoint (w • (1 : B(𝓗))) := by
      rw [← hHK]
      exact (H.2).sub K.2
    have hwreal : (starRingEnd ℂ) w = w := by
      have := hselfadjoint
      rw [IsSelfAdjoint, star_smul, star_one] at this
      exact smul_left_injective ℂ (one_ne_zero) this
    have himzero : w.im = 0 := Complex.conj_eq_iff_im.mp hwreal
    refine ⟨w.re, ?_⟩
    apply Subtype.ext
    show (H : B(𝓗)) = (K : B(𝓗)) + (w.re : ℝ) • (1 : B(𝓗))
    have hwre : w = (w.re : ℂ) := Complex.ext rfl himzero
    have hc : (w.re : ℝ) • (1 : B(𝓗)) = w • (1 : B(𝓗)) := by
      have h' : ((w.re : ℝ) : ℂ) = algebraMap ℝ ℂ (w.re : ℝ) := by norm_cast
      rw [show (w.re : ℝ) • (1 : B(𝓗)) = ((w.re : ℝ) : ℂ) • (1 : B(𝓗)) from by
        rw [h', IsScalarTower.algebraMap_smul], ← hwre]
    rw [hc, ← hHK]
    abel
  · rintro ⟨c, h⟩
    exact hamiltonianFlow_eq_of_eq_add_smul_one ℏ H K c h

/-- The automorphism-level classification: two Hamiltonians generate conjugate flows exactly when
they agree up to a change of representation `β` and a real scalar shift. Combines
`hamiltonianFlow_map` (to reduce the `β`-conjugate flow to a flow at the fixed representation
`β(H)`) with `hamiltonianFlow_eq_iff`. -/
theorem hamiltonianFlow_conj_iff (ℏ : ℝ) (hℏ : ℏ ≠ 0) [Nontrivial (B(𝓗))]
    (β : B(𝓗) ≃⋆ₐ[ℂ] B(𝓗)) (H K : Observable (B(𝓗))) :
    hamiltonianFlow ℏ K = (hamiltonianFlow ℏ H).conj β ↔ ∃ c : ℝ, K = β.observable H + c • 1 := by
  rw [← hamiltonianFlow_map]
  exact hamiltonianFlow_eq_iff ℏ hℏ K (β.observable H)

/-- The physical/unitary packaging of `hamiltonianFlow_conj_iff`: two Hamiltonians generate flows
related by *some* automorphism of `B(𝓗)` exactly when one is a unitary conjugate of the other, up
to a real scalar shift. Every ⋆-automorphism of `B(𝓗)` is implemented by unitary conjugation
(`conjStarAlgAut_surjective`), so replacing `β` by an existential over `B(𝓗) ≃⋆ₐ[ℂ] B(𝓗)` with an
existential over unitaries loses nothing; no quotient type (e.g. `ProjectiveUnitary`) is needed to
state this, since the existential over `V` already absorbs the phase ambiguity that
`ProjectiveUnitary`/`PU.mulEquivAut` package separately as the static statement
`Aut⋆(B(𝓗)) ≅ PU(𝓗)`. -/
theorem hamiltonianFlow_iff_exists_unitary (ℏ : ℝ) (hℏ : ℏ ≠ 0) [Nontrivial (B(𝓗))]
    (H K : Observable (B(𝓗))) :
    (∃ β : B(𝓗) ≃⋆ₐ[ℂ] B(𝓗), hamiltonianFlow ℏ K = (hamiltonianFlow ℏ H).conj β) ↔
      ∃ (V : unitary (B(𝓗))) (c : ℝ),
        (K : B(𝓗)) = (V : B(𝓗)) * (H : B(𝓗)) * star (V : B(𝓗)) + c • 1 := by
  constructor
  · rintro ⟨β, hβ⟩
    obtain ⟨V, hV⟩ := conjStarAlgAut_surjective (H := 𝓗) β
    obtain ⟨c, hc⟩ := (hamiltonianFlow_conj_iff ℏ hℏ β H K).mp hβ
    refine ⟨V, c, ?_⟩
    have := congrArg (Subtype.val (p := fun x : B(𝓗) => IsSelfAdjoint x)) hc
    simpa [← hV, Unitary.conjStarAlgAut_apply] using this
  · rintro ⟨V, c, hc⟩
    refine ⟨Unitary.conjStarAlgAut ℂ (B(𝓗)) V, ?_⟩
    apply hamiltonianFlow_map_add_smul_one ℏ (Unitary.conjStarAlgAut ℂ (B(𝓗)) V) H K c
    apply Subtype.ext
    simpa [Unitary.conjStarAlgAut_apply] using hc

end UnitaryOneParameterGroup

end OperatorAlgebra
