/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.Unbounded.QuantumMechanics.OperatorAlgebra.Basic
public import PhyslibAlpha.Unbounded.QuantumMechanics.OperatorAlgebra.Dynamics.CPClosure
public import Mathlib.Analysis.Normed.Algebra.Exponential
public import Mathlib.Analysis.Calculus.Deriv.Mul
public import Mathlib.Analysis.Calculus.FDeriv.RestrictScalars
public import Mathlib.Analysis.ODE.ExistUnique
public import Mathlib.Analysis.Normed.Ring.Units
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus

/-!
# Quantum dynamical semigroups

In the Heisenberg picture, an irreversible quantum dynamics is a family of unital completely
positive maps indexed by nonnegative time.  This file records that structure without committing to
a generator or to a Hilbert-space representation.
-/

@[expose] public section

namespace OperatorAlgebra

open scoped NNReal

variable {A : Type*} [OperatorAlgebra A]

noncomputable local instance : NormedAlgebra ℚ (A →L[ℂ] A) :=
  .restrictScalars ℚ ℂ (A →L[ℂ] A)

/-- A (not yet assumed continuous) Heisenberg quantum dynamical semigroup.

The maps are `Channel`s, hence unital and completely positive.  Continuity is kept as an explicit
field because the algebraic semigroup axioms alone do not provide a generator.
-/
structure QuantumDynamicalSemigroup (A : Type*) [OperatorAlgebra A] where
  /-- The channel at each nonnegative time. -/
  map : ℝ≥0 → Channel A A
  /-- Time zero is the identity, pointwise. -/
  map_zero : ∀ a, map 0 a = a
  /-- Evolution composes according to addition of times. -/
  map_add : ∀ s t a, map (s + t) a = map s (map t a)
  /-- Pointwise continuity in time. -/
  continuous : ∀ a, Continuous (fun t => map t a)

namespace QuantumDynamicalSemigroup

/-- Regard each channel in a dynamical semigroup as its canonical bounded linear map. -/
noncomputable def continuousLinearMap (Φ : QuantumDynamicalSemigroup A) (t : ℝ≥0) :
    A →L[ℂ] A :=
  completelyPositiveMap_toContinuousLinearMap (Φ.map t).1

@[simp]
lemma continuousLinearMap_apply (Φ : QuantumDynamicalSemigroup A) (t : ℝ≥0) (a : A) :
    Φ.continuousLinearMap t a = Φ.map t a := by
  show completelyPositiveMap_toContinuousLinearMap (Φ.map t).1 a = _
  rw [completelyPositiveMap_toContinuousLinearMap_apply]

@[simp]
lemma continuousLinearMap_zero (Φ : QuantumDynamicalSemigroup A) :
    Φ.continuousLinearMap 0 = (1 : A →L[ℂ] A) := by
  ext a
  simp [continuousLinearMap_apply, Φ.map_zero a]

lemma continuousLinearMap_add (Φ : QuantumDynamicalSemigroup A) (s t : ℝ≥0) :
    Φ.continuousLinearMap (s + t) =
      Φ.continuousLinearMap s * Φ.continuousLinearMap t := by
  ext a
  simp only [continuousLinearMap_apply, mul_apply_eq_comp]
  rw [Φ.map_add]

/-- Operator-norm continuity of a quantum dynamical semigroup. -/
def IsNormContinuous (Φ : QuantumDynamicalSemigroup A) : Prop :=
  Continuous Φ.continuousLinearMap

@[simp]
lemma map_zero_apply (Φ : QuantumDynamicalSemigroup A) (a : A) :
    Φ.map 0 a = a :=
  Φ.map_zero a

lemma map_add_apply (Φ : QuantumDynamicalSemigroup A) (s t : ℝ≥0) (a : A) :
    Φ.map (s + t) a = Φ.map s (Φ.map t a) :=
  Φ.map_add s t a

end QuantumDynamicalSemigroup

section Bounded

variable {A : Type*} [OperatorAlgebra A]

/-- A quantum dynamical semigroup with a bounded generator.

The channel-valued semigroup remains the primary object.  The generator field records the
additional boundedness information, while `map_eq_exp` states that the semigroup is the
corresponding Banach-space exponential.  This is the interface used by the bounded GKSL theory;
it does not assert the converse classification theorem. -/
structure BoundedQuantumDynamicalSemigroup (A : Type*) [OperatorAlgebra A]
    extends QuantumDynamicalSemigroup A where
  /-- The bounded infinitesimal generator. -/
  generator : A →L[ℂ] A
  /-- The semigroup is the exponential generated by `generator`. -/
  map_eq_exp : ∀ (t : ℝ≥0) (a : A),
    toQuantumDynamicalSemigroup.map t a =
      NormedSpace.exp ((t : ℂ) • generator) a

namespace BoundedQuantumDynamicalSemigroup

lemma isNormContinuous (Φ : BoundedQuantumDynamicalSemigroup A) :
    QuantumDynamicalSemigroup.IsNormContinuous Φ.toQuantumDynamicalSemigroup := by
  change Continuous (fun t : ℝ≥0 =>
    Φ.toQuantumDynamicalSemigroup.continuousLinearMap t)
  have hmap : (fun t : ℝ≥0 =>
      Φ.toQuantumDynamicalSemigroup.continuousLinearMap t) =
      (fun t : ℝ≥0 => NormedSpace.exp ((t : ℂ) • Φ.generator)) := by
    funext t
    ext a
    rw [QuantumDynamicalSemigroup.continuousLinearMap_apply]
    exact Φ.map_eq_exp t a
  rw [hmap]
  apply NormedSpace.exp_continuous.comp
  fun_prop

lemma map_eq_exp_clm (Φ : BoundedQuantumDynamicalSemigroup A) (t : ℝ≥0) :
    Φ.toQuantumDynamicalSemigroup.continuousLinearMap t =
      NormedSpace.exp ((t : ℂ) • Φ.generator) := by
  ext a
  rw [QuantumDynamicalSemigroup.continuousLinearMap_apply]
  exact Φ.map_eq_exp t a

/-! ### Uniqueness from the bounded generator -/

/-- Two bounded semigroup realizations with the same generator have the same time evolution.

This is the uniqueness half of the bounded-generator classification.  It is deliberately stated
pointwise on observables, so it applies without requiring an extensionality theorem for the
channel-valued structures themselves.
-/
theorem map_eq_of_generator_eq
    (Φ Ψ : BoundedQuantumDynamicalSemigroup A)
    (h : Φ.generator = Ψ.generator) :
    ∀ (t : ℝ≥0) (a : A),
      Φ.toQuantumDynamicalSemigroup.map t a =
        Ψ.toQuantumDynamicalSemigroup.map t a := by
  intro t a
  rw [Φ.map_eq_exp, Ψ.map_eq_exp, h]

/-! ### The generator as a genuine right derivative

The exponential field is not merely a convenient formula: it identifies the infinitesimal
generator.  We state this using a real right derivative, since physical time is restricted to
`t ≥ 0`.  Keeping the derivative theorem here makes later Hamiltonian and GKSL APIs independent
of the particular way in which a semigroup was constructed.
-/

/-- Extend a nonnegative time to a real parameter by truncating negative values at zero. -/
def nonnegativeTime (t : ℝ) : ℝ≥0 :=
  ⟨max t 0, le_max_right _ _⟩

@[simp]
lemma nonnegativeTime_of_nonneg {t : ℝ} (ht : 0 ≤ t) :
    nonnegativeTime t = ⟨t, ht⟩ := by
  ext
  simp [nonnegativeTime, max_eq_left ht]

private lemma hasDerivAt_exp_apply_of_generator
    (G : A →L[ℂ] A) (a : A) :
    HasDerivAt
      (fun t : ℝ => (NormedSpace.exp ((t : ℂ) • G)) a)
      (G a) 0 := by
  have hexpC := (hasDerivAt_exp_smul_const (𝕂 := ℂ)
    (𝔸 := A →L[ℂ] A) G (0 : ℂ))
  have hexpC' : HasDerivAt (fun u : ℂ => NormedSpace.exp (u • G)) G 0 := by
    have h0 : (0 : ℂ) • G = 0 := zero_smul ℂ G
    rw [h0, NormedSpace.exp_zero, one_mul] at hexpC
    exact hexpC
  have hconstC : HasDerivAt (fun _ : ℂ => a) 0 0 :=
    hasDerivAt_const (x := (0 : ℂ)) (c := a)
  have happlyC := HasDerivAt.clm_apply (F := A) (G := A) hexpC' hconstC
  have happlyC' : HasDerivAt
      (fun y : ℂ => (NormedSpace.exp (y • G)) a) (G a) 0 := by
    have h0 : (0 : ℂ) • G = 0 := zero_smul ℂ G
    rw [h0, NormedSpace.exp_zero, one_apply_eq_self, add_zero] at happlyC
    exact happlyC
  have houterR := happlyC'.hasFDerivAt.restrictScalars ℝ
  have hinner : HasFDerivAt (fun t : ℝ => (t : ℂ)) Complex.ofRealCLM 0 :=
    Complex.ofRealCLM.hasFDerivAt
  have houterR' : HasFDerivAt
      (fun y : ℂ => (NormedSpace.exp (y • G)) a)
      (ContinuousLinearMap.restrictScalars ℝ
        (ContinuousLinearMap.toSpanSingleton ℂ (G a)))
      (Complex.ofReal (0 : ℝ)) := by
    simpa using houterR
  have happly := houterR'.comp (0 : ℝ) hinner
  simpa [Function.comp_def, ContinuousLinearMap.toSpanSingleton_apply_one] using
    happly.hasDerivAt

lemma hasDerivAt_exp_apply (Φ : BoundedQuantumDynamicalSemigroup A) (a : A) :
    HasDerivAt
      (fun t : ℝ => (NormedSpace.exp ((t : ℂ) • Φ.generator)) a)
      (Φ.generator a) 0 := by
  exact hasDerivAt_exp_apply_of_generator Φ.generator a

lemma hasDerivWithinAt_generator (Φ : BoundedQuantumDynamicalSemigroup A) (a : A) :
    HasDerivWithinAt
      (fun t : ℝ => Φ.toQuantumDynamicalSemigroup.map (nonnegativeTime t) a)
      (Φ.generator a) (Set.Ici 0) 0 := by
  have h := (Φ.hasDerivAt_exp_apply a).hasDerivWithinAt (s := Set.Ici 0)
  apply h.congr
  · intro t ht
    rw [nonnegativeTime_of_nonneg ht]
    have h := Φ.map_eq_exp ⟨t, ht⟩ a
    change Φ.toQuantumDynamicalSemigroup.map ⟨t, ht⟩ a =
      (NormedSpace.exp (((⟨t, ht⟩ : ℝ≥0) : ℂ) • Φ.generator)) a at h
    have hcoerce : ((⟨t, ht⟩ : ℝ≥0) : ℂ) = (t : ℂ) := by
      rfl
    rw [hcoerce] at h
    exact h
  · rw [nonnegativeTime_of_nonneg (by simp)]
    have hzero : (⟨0, by simp⟩ : ℝ≥0) = 0 := by
      apply Subtype.ext
      simp
    rw [hzero]
    have h := Φ.map_eq_exp 0 a
    change Φ.toQuantumDynamicalSemigroup.map 0 a =
      (NormedSpace.exp (((0 : ℝ≥0) : ℂ) • Φ.generator)) a at h
    exact h

/-- A bounded semigroup generator is unique among right-derivative certificates. -/
lemma generator_eq_of_hasDerivWithinAt
    (Φ : BoundedQuantumDynamicalSemigroup A) (L : A →L[ℂ] A)
    (hL : ∀ a,
      HasDerivWithinAt
        (fun t : ℝ => Φ.toQuantumDynamicalSemigroup.map (nonnegativeTime t) a)
        (L a) (Set.Ici 0) 0) :
    L = Φ.generator := by
  ext a
  have hL' := hL a
  have hG' := Φ.hasDerivWithinAt_generator a
  have heq := (uniqueDiffWithinAt_Ici (0 : ℝ)).eq
    hL'.hasFDerivWithinAt hG'.hasFDerivWithinAt
  have heq' := congrArg (fun f => f (1 : ℝ)) heq
  simpa [ContinuousLinearMap.toSpanSingleton_apply_one] using heq'

lemma exp_apply_of_apply_eq_zero
    (G : A →L[ℂ] A) (a : A) (hG : G a = 0) (z : ℂ) :
    (NormedSpace.exp (z • G)) a = a := by
  rw [NormedSpace.exp_eq_tsum ℂ]
  let ev : (A →L[ℂ] A) →L[ℂ] A := ContinuousLinearMap.apply ℂ A a
  have hsum : Summable (fun n : ℕ => (Nat.factorial n : ℂ)⁻¹ • (z • G) ^ n) := by
    exact NormedSpace.expSeries_summable' (z • G)
  change (∑' n : ℕ, (Nat.factorial n : ℂ)⁻¹ • (z • G) ^ n) a = a
  change ev (∑' n : ℕ, (Nat.factorial n : ℂ)⁻¹ • (z • G) ^ n) = a
  rw [ev.map_tsum hsum]
  have hsingle :
      (∑' n : ℕ, ev ((Nat.factorial n : ℂ)⁻¹ • (z • G) ^ n)) =
        ev ((Nat.factorial 0 : ℂ)⁻¹ • (z • G) ^ 0) := by
    apply tsum_eq_single 0
    intro n hn
    have hpow : ((z • G) ^ n) a = 0 := by
      induction n with
      | zero => exact False.elim (hn rfl)
      | succ n ih =>
          rw [pow_succ]
          change ((z • G) ^ n) ((z • G) a) = 0
          rw [smul_apply, hG, smul_zero]
          exact map_zero ((z • G) ^ n)
    simp [ev, hpow]
  rw [hsingle]
  simp [ev]

lemma generator_isUnital (Φ : BoundedQuantumDynamicalSemigroup A) :
    Φ.generator 1 = 0 := by
  have h := Φ.hasDerivWithinAt_generator (1 : A)
  have hmap : Set.EqOn
      (fun t : ℝ => Φ.toQuantumDynamicalSemigroup.map (nonnegativeTime t) (1 : A))
      (fun _ : ℝ => (1 : A)) (Set.Ici 0) := by
    intro t ht
    change Φ.toQuantumDynamicalSemigroup.map (nonnegativeTime t) (1 : A) = 1
    rw [nonnegativeTime_of_nonneg ht]
    exact (Φ.toQuantumDynamicalSemigroup.map ⟨t, ht⟩).2
  have hzero := h.congr
    (fun t ht => (hmap (x := t) ht).symm)
    (hmap (x := 0) (by simp)).symm
  have hconst' := hasDerivAt_const (x := (0 : ℝ)) (c := (1 : A))
  have heq := (uniqueDiffWithinAt_Ici (0 : ℝ)).eq
    hzero.hasFDerivWithinAt hconst'.hasFDerivAt.hasFDerivWithinAt
  have heq' := congrArg (fun f => f (1 : ℝ)) heq
  simpa [ContinuousLinearMap.toSpanSingleton_apply_one] using heq'

@[simp]
lemma map_zero_apply (Φ : BoundedQuantumDynamicalSemigroup A) (a : A) :
    Φ.toQuantumDynamicalSemigroup.map 0 a = a :=
  Φ.toQuantumDynamicalSemigroup.map_zero a

lemma map_add_apply (Φ : BoundedQuantumDynamicalSemigroup A) (s t : ℝ≥0) (a : A) :
    Φ.toQuantumDynamicalSemigroup.map (s + t) a =
      Φ.toQuantumDynamicalSemigroup.map s
        (Φ.toQuantumDynamicalSemigroup.map t a) :=
  Φ.toQuantumDynamicalSemigroup.map_add s t a

end BoundedQuantumDynamicalSemigroup

end Bounded

/-! ### Exponential identification from a derivative certificate -/

namespace QuantumDynamicalSemigroup

variable {A : Type*} [OperatorAlgebra A]

/-- A candidate bounded generator together with its right derivative at time zero.

Pointwise continuity and the semigroup law do not by themselves provide differentiability.  This
certificate records precisely the extra analytic input needed to identify the semigroup with an
exponential; it is deliberately independent of finite-dimensional matrix coordinates. -/
structure HasBoundedGenerator (Φ : QuantumDynamicalSemigroup A) where
  /-- The bounded infinitesimal generator. -/
  generator : A →L[ℂ] A
  /-- The right derivative of the orbit at time zero. -/
  has_deriv : ∀ a,
    HasDerivWithinAt
      (fun t : ℝ => Φ.map (BoundedQuantumDynamicalSemigroup.nonnegativeTime t) a)
      (generator a) (Set.Ici 0) 0

namespace HasBoundedGenerator

variable {Φ : QuantumDynamicalSemigroup A}
variable (G : HasBoundedGenerator Φ)

/-- The derivative certificate at zero propagates to every nonnegative time by the semigroup law. -/
private lemma hasDerivWithinAt_at
    (a : A) {t : ℝ} (ht : 0 ≤ t) :
    HasDerivWithinAt
      (fun s : ℝ => Φ.map (BoundedQuantumDynamicalSemigroup.nonnegativeTime s) a)
      (G.generator (Φ.map (⟨t, ht⟩ : ℝ≥0) a)) (Set.Ici t) t := by
  let Y : A := Φ.map (⟨t, ht⟩ : ℝ≥0) a
  have hbase := G.has_deriv Y
  have hinner : HasDerivWithinAt (fun s : ℝ => s - t) 1 (Set.Ici t) t :=
    ((hasDerivAt_id t).sub_const t).hasDerivWithinAt
  have hmaps : Set.MapsTo (fun s : ℝ => s - t) (Set.Ici t) (Set.Ici 0) := by
    intro s hs
    change t ≤ s at hs
    exact sub_nonneg.mpr hs
  have hshift := HasDerivWithinAt.scomp_of_eq (𝕜' := ℝ) t
    (h := fun s : ℝ => s - t)
    (g₁ := fun u : ℝ =>
      Φ.map (BoundedQuantumDynamicalSemigroup.nonnegativeTime u) Y)
    (g₁' := G.generator Y) (y := 0) hbase hinner hmaps (by simp)
  have hcongr := HasDerivWithinAt.congr
    (f₁ := fun s : ℝ => Φ.map (BoundedQuantumDynamicalSemigroup.nonnegativeTime s) a)
    hshift
    (by
      intro s hs
      have hs0 : 0 ≤ s := le_trans ht hs
      have hst : 0 ≤ s - t := sub_nonneg.mpr (by
        change t ≤ s at hs
        exact hs)
      have heq : BoundedQuantumDynamicalSemigroup.nonnegativeTime s =
          BoundedQuantumDynamicalSemigroup.nonnegativeTime (s - t) +
            BoundedQuantumDynamicalSemigroup.nonnegativeTime t := by
        apply Subtype.ext
        change max s 0 = max (s - t) 0 + max t 0
        rw [max_eq_left hs0, max_eq_left hst, max_eq_left ht]
        ring
      have htmap : BoundedQuantumDynamicalSemigroup.nonnegativeTime t =
          (⟨t, ht⟩ : ℝ≥0) :=
        BoundedQuantumDynamicalSemigroup.nonnegativeTime_of_nonneg ht
      rw [heq, Φ.map_add]
      have hY : Φ.map (BoundedQuantumDynamicalSemigroup.nonnegativeTime t) a = Y := by
        dsimp [Y]
        rw [htmap]
      rw [hY]
      rfl)
    (by
      have hzero : BoundedQuantumDynamicalSemigroup.nonnegativeTime t =
          (⟨t, ht⟩ : ℝ≥0) :=
        BoundedQuantumDynamicalSemigroup.nonnegativeTime_of_nonneg ht
      simp only [Function.comp_apply]
      rw [show t - t = 0 by ring]
      have hnt : BoundedQuantumDynamicalSemigroup.nonnegativeTime 0 = 0 := by
        apply Subtype.ext
        simp [BoundedQuantumDynamicalSemigroup.nonnegativeTime]
      rw [hnt, Φ.map_zero, hzero])
  simpa [Function.comp_def, one_smul, Y] using hcongr

/-- The exponential orbit has the expected differential equation at every real time. -/
private lemma exp_apply_hasDerivAt (G : HasBoundedGenerator Φ) (a : A) (t : ℝ) :
    HasDerivAt
      (fun s : ℝ => (NormedSpace.exp ((s : ℂ) • G.generator)) a)
      ((NormedSpace.exp ((t : ℂ) • G.generator)) (G.generator a)) t := by
  let Y : A := (NormedSpace.exp ((t : ℂ) • G.generator)) a
  have hbase := BoundedQuantumDynamicalSemigroup.hasDerivAt_exp_apply_of_generator
    G.generator Y
  have hinner : HasDerivAt (fun s : ℝ => s - t) 1 t :=
    (hasDerivAt_id t).sub_const t
  have hshift := HasDerivAt.scomp_of_eq t
    (h := fun s : ℝ => s - t)
    (g₁ := fun u : ℝ =>
      (NormedSpace.exp ((u : ℂ) • G.generator)) Y)
    (g₁' := G.generator Y) (y := 0) hbase hinner (by simp)
  have heqfun :
      (fun s : ℝ => (NormedSpace.exp ((s : ℂ) • G.generator)) a) =ᶠ[nhds t]
        ((fun u : ℝ =>
          (NormedSpace.exp ((u : ℂ) • G.generator)) Y) ∘ fun s => s - t) :=
    Filter.Eventually.of_forall (by
      intro s
      have hcomm : Commute
          (((s - t : ℝ) : ℂ) • G.generator)
          (((t : ℝ) : ℂ) • G.generator) := by
        rw [commute_iff_eq]
        ext b
        change ((s - t : ℝ) : ℂ) • G.generator
            (((t : ℝ) : ℂ) • G.generator b) =
          ((t : ℝ) : ℂ) • G.generator
            (((s - t : ℝ) : ℂ) • G.generator b)
        rw [map_smul, map_smul, smul_smul, smul_smul]
        congr 1
        ring
      have hsum : ((s - t : ℝ) : ℂ) • G.generator +
            ((t : ℝ) : ℂ) • G.generator = (s : ℂ) • G.generator := by
        calc
          _ = ((((s - t : ℝ) : ℂ) + (t : ℂ)) • G.generator) :=
            (add_smul _ _ _).symm
          _ = (s : ℂ) • G.generator := by
            congr 1
            push_cast
            ring
      have hexp :
          NormedSpace.exp (((s - t : ℝ) : ℂ) • G.generator) *
              NormedSpace.exp (((t : ℝ) : ℂ) • G.generator) =
            NormedSpace.exp ((s : ℂ) • G.generator) := by
        rw [← NormedSpace.exp_add_of_commute hcomm, hsum]
      dsimp only [Function.comp_apply, Y]
      rw [← hexp]
      rw [mul_apply_eq_comp])
  have hcongr := hshift.congr_of_eventuallyEq heqfun
  have hcomm : Commute G.generator
      (NormedSpace.exp ((t : ℂ) • G.generator)) := by
    have hscalar : Commute G.generator ((t : ℂ) • G.generator) := by
      rw [commute_iff_eq]
      ext b
      change G.generator (((t : ℝ) : ℂ) • G.generator b) =
        ((t : ℝ) : ℂ) • G.generator (G.generator b)
      rw [map_smul]
    exact hscalar.exp_right
  have hderiv : G.generator ((NormedSpace.exp ((t : ℂ) • G.generator)) a) =
      (NormedSpace.exp ((t : ℂ) • G.generator)) (G.generator a) := by
    change (G.generator * NormedSpace.exp ((t : ℂ) • G.generator)) a =
      (NormedSpace.exp ((t : ℂ) • G.generator) * G.generator) a
    rw [hcomm.eq]
  simpa [Y, hderiv] using hcongr

/-- A bounded derivative certificate determines the semigroup uniquely as an exponential. -/
lemma map_eq_exp_of_hasBoundedGenerator
    (G : HasBoundedGenerator Φ) (a : A) (t : ℝ≥0) :
    Φ.map t a = NormedSpace.exp ((t : ℂ) • G.generator) a := by
  let f : ℝ → A := fun s => Φ.map
    (BoundedQuantumDynamicalSemigroup.nonnegativeTime s) a
  let g : ℝ → A := fun s =>
    (NormedSpace.exp ((s : ℂ) • G.generator)) a
  let Gℝ : A →L[ℝ] A := G.generator.restrictScalars ℝ
  have htime : Continuous
      (BoundedQuantumDynamicalSemigroup.nonnegativeTime : ℝ → ℝ≥0) := by
    change Continuous (fun s : ℝ =>
      (⟨max s 0, le_max_right _ _⟩ : ℝ≥0))
    exact (continuous_id.max continuous_const).subtype_mk fun _ => le_max_right _ _
  have hf : Continuous f := by
    exact (Φ.continuous a).comp htime
  have hg₀ : Continuous (fun s : ℝ =>
      NormedSpace.exp ((s : ℂ) • G.generator)) := by
    apply NormedSpace.exp_continuous.comp
    exact (Complex.continuous_ofReal.comp continuous_id).smul continuous_const
  have hg : Continuous g := by
    exact hg₀.clm_apply continuous_const
  have hflipschitz : ∀ s : ℝ, LipschitzWith ‖Gℝ‖₊ (fun x : A => Gℝ x) := by
    intro s
    exact Gℝ.lipschitz
  have hfderiv : ∀ s ∈ Set.Ico (0 : ℝ) (t : ℝ),
      HasDerivWithinAt f (Gℝ (f s)) (Set.Ici s) s := by
    intro s hs
    have hs0 : 0 ≤ s := hs.1
    have h := G.hasDerivWithinAt_at a hs0
    simpa [f, Gℝ, BoundedQuantumDynamicalSemigroup.nonnegativeTime_of_nonneg hs0] using h
  have hgderiv : ∀ s ∈ Set.Ico (0 : ℝ) (t : ℝ),
      HasDerivWithinAt g (Gℝ (g s)) (Set.Ici s) s := by
    intro s hs
    have h := G.exp_apply_hasDerivAt a s
    have hcomm : Commute G.generator
        (NormedSpace.exp ((s : ℂ) • G.generator)) := by
      have hscalar : Commute G.generator ((s : ℂ) • G.generator) := by
        rw [commute_iff_eq]
        ext b
        change G.generator (((s : ℝ) : ℂ) • G.generator b) =
          ((s : ℝ) : ℂ) • G.generator (G.generator b)
        rw [map_smul]
      exact hscalar.exp_right
    have hderiv : G.generator ((NormedSpace.exp ((s : ℂ) • G.generator)) a) =
        (NormedSpace.exp ((s : ℂ) • G.generator)) (G.generator a) := by
      change (G.generator * NormedSpace.exp ((s : ℂ) • G.generator)) a =
        (NormedSpace.exp ((s : ℂ) • G.generator) * G.generator) a
      rw [hcomm.eq]
    have h' := h.hasDerivWithinAt (s := Set.Ici s)
    simpa [g, Gℝ, hderiv] using h'
  have h0 : f 0 = g 0 := by
    dsimp [f, g]
    have hnt : BoundedQuantumDynamicalSemigroup.nonnegativeTime 0 = 0 := by
      apply Subtype.ext
      simp [BoundedQuantumDynamicalSemigroup.nonnegativeTime]
    rw [hnt, Φ.map_zero]
    rw [zero_smul ℂ G.generator, NormedSpace.exp_zero]
    rfl
  have heq := ODE_solution_unique (a := (0 : ℝ)) (b := (t : ℝ))
    hflipschitz hf.continuousOn hfderiv (hg.continuousOn) hgderiv h0
  have ht := heq (by exact ⟨by simp, le_rfl⟩)
  have ht' : BoundedQuantumDynamicalSemigroup.nonnegativeTime (t : ℝ) = t := by
    apply Subtype.ext
    simp [BoundedQuantumDynamicalSemigroup.nonnegativeTime]
  change Φ.map (BoundedQuantumDynamicalSemigroup.nonnegativeTime (t : ℝ)) a =
      (NormedSpace.exp (((t : ℝ) : ℂ) • G.generator)) a at ht
  rw [ht'] at ht
  exact ht

/-- Package a derivative-certified semigroup as a bounded exponential semigroup. -/
noncomputable def toBoundedQuantumDynamicalSemigroup
    (G : HasBoundedGenerator Φ) : BoundedQuantumDynamicalSemigroup A where
  toQuantumDynamicalSemigroup := Φ
  generator := G.generator
  map_eq_exp := by
    intro t a
    exact G.map_eq_exp_of_hasBoundedGenerator a t

@[simp]
lemma toBoundedQuantumDynamicalSemigroup_generator
    (G : HasBoundedGenerator Φ) :
    G.toBoundedQuantumDynamicalSemigroup.generator = G.generator :=
  rfl

end HasBoundedGenerator

end QuantumDynamicalSemigroup

namespace BoundedQuantumDynamicalSemigroup

variable {A : Type*} [OperatorAlgebra A]

/-- Extract the derivative certificate carried by an already packaged bounded semigroup. -/
noncomputable def toHasBoundedGenerator
    (Φ : BoundedQuantumDynamicalSemigroup A) :
    QuantumDynamicalSemigroup.HasBoundedGenerator Φ.toQuantumDynamicalSemigroup where
  generator := Φ.generator
  has_deriv := Φ.hasDerivWithinAt_generator

@[simp]
lemma toHasBoundedGenerator_generator
    (Φ : BoundedQuantumDynamicalSemigroup A) :
    Φ.toHasBoundedGenerator.generator = Φ.generator :=
  rfl

end BoundedQuantumDynamicalSemigroup

/-! ### The generator of a norm-continuous semigroup

The preceding API accepts a derivative certificate.  In a Banach algebra that certificate is
automatic for a norm-continuous semigroup.  The proof below is the standard integrated-semigroup
argument: the integral over a sufficiently short interval is invertible, and the semigroup law
expresses the original curve as a difference quotient involving that integral.

The argument is deliberately stated for curves in a general normed algebra.  The specialization
to curves of bounded operators is then a short application of `HasDerivWithinAt.clm_apply`.
-/

section NormContinuousGenerator

open scoped Interval Topology
open MeasureTheory intervalIntegral Filter

noncomputable local instance semigroupRealNormedAlgebra :
    NormedAlgebra ℝ (A →L[ℂ] A) :=
  .restrictScalars ℝ ℂ (A →L[ℂ] A)

noncomputable local instance semigroupComplexScalarTower :
    IsScalarTower ℂ (A →L[ℂ] A) (A →L[ℂ] A) := by
  constructor
  intro r f g
  ext a
  simp [ContinuousLinearMap.smul_comp, ContinuousLinearMap.comp_smul]

noncomputable local instance semigroupComplexSmulCommClass :
    SMulCommClass ℂ (A →L[ℂ] A) (A →L[ℂ] A) := by
  constructor
  intro r f g
  ext a
  simp [ContinuousLinearMap.smul_comp, ContinuousLinearMap.comp_smul]

noncomputable local instance semigroupRealScalarTower :
    IsScalarTower ℝ (A →L[ℂ] A) (A →L[ℂ] A) := by
  constructor
  intro r f g
  ext a
  simp [ContinuousLinearMap.smul_comp, ContinuousLinearMap.comp_smul]

noncomputable local instance semigroupRealSmulCommClass :
    SMulCommClass ℝ (A →L[ℂ] A) (A →L[ℂ] A) := by
  constructor
  intro r f g
  ext a
  simp [ContinuousLinearMap.smul_comp, ContinuousLinearMap.comp_smul]

/-- The integral of an operator-valued curve from zero to `t`. -/
noncomputable def integratedContinuousLinearMap
    (T : ℝ → (A →L[ℂ] A)) (t : ℝ) : A →L[ℂ] A :=
  ∫ x in (0 : ℝ)..t, T x

lemma integratedContinuousLinearMap_continuous
    (T : ℝ → (A →L[ℂ] A)) (hT : Continuous T) :
    Continuous (integratedContinuousLinearMap T) := by
  exact (differentiable_integral_of_continuous hT).continuous

private lemma integratedContinuousLinearMap_hasDerivAt
    (T : ℝ → (A →L[ℂ] A)) (hT : Continuous T) (t : ℝ) :
    HasDerivAt (integratedContinuousLinearMap T) (T t) t := by
  exact intervalIntegral.integral_hasDerivAt_right
    (hT.intervalIntegrable _ _) (hT.stronglyMeasurableAtFilter volume (𝓝 t))
      hT.continuousAt

lemma integratedContinuousLinearMap_add_sub
    (T : ℝ → (A →L[ℂ] A)) (hT : Continuous T) (a h : ℝ) :
    integratedContinuousLinearMap T (h + a) - integratedContinuousLinearMap T h =
      ∫ x in h..h+a, T x := by
  have hsplit := intervalIntegral.integral_add_adjacent_intervals
    (f := T) (μ := volume) (a := (0 : ℝ)) (b := h) (c := h + a)
    (hT.intervalIntegrable (μ := volume) _ _) (hT.intervalIntegrable (μ := volume) _ _)
  change (∫ x in 0..h + a, T x) - ∫ x in 0..h, T x = _
  rw [← hsplit]
  abel

private lemma integratedContinuousLinearMap_shift
    (T : ℝ → (A →L[ℂ] A)) (hT : Continuous T)
    (hsemigroup : ∀ {s t : ℝ}, 0 ≤ s → 0 ≤ t → T (s + t) = T s * T t)
    {a h : ℝ} (ha : 0 ≤ a) (hh : 0 ≤ h) :
    integratedContinuousLinearMap T (h + a) - integratedContinuousLinearMap T h =
      T h * integratedContinuousLinearMap T a := by
  rw [integratedContinuousLinearMap_add_sub T hT]
  have hshift := intervalIntegral.integral_comp_add_right
    (f := T) (a := (0 : ℝ)) (b := a) h
  calc
    (∫ x in h..h + a, T x) = ∫ x in 0..a, T (x + h) := by
      rw [hshift]
      simp [add_comm]
    _ = ∫ x in 0..a, T h * T x := by
      apply intervalIntegral.integral_congr
      intro x hx
      change T (x + h) = T h * T x
      have hx' : x ∈ Set.Icc (0 : ℝ) a := by
        rcases Set.mem_uIcc.mp hx with hx' | hx'
        · exact hx'
        · constructor <;> linarith [hx'.1, hx'.2]
      simpa [add_comm] using hsemigroup hh hx'.1
    _ = T h * integratedContinuousLinearMap T a := by
      rw [integratedContinuousLinearMap]
      change (∫ x in 0..a,
        (ContinuousLinearMap.mul ℝ (A →L[ℂ] A) (T h)) (T x)) = _
      have hi : IntervalIntegrable T volume 0 a :=
        hT.intervalIntegrable (μ := volume) (0 : ℝ) a
      rw [ContinuousLinearMap.intervalIntegral_comp_comm _ hi]
      rfl

private theorem hasDerivWithinAt_of_integratedContinuousLinearMap_isUnit
    (T : ℝ → (A →L[ℂ] A)) (hT : Continuous T)
    (hzero : T 0 = 1)
    (hsemigroup : ∀ {s t : ℝ}, 0 ≤ s → 0 ≤ t → T (s + t) = T s * T t)
    {a : ℝ} (ha : 0 < a)
    (haunit : IsUnit (integratedContinuousLinearMap T a)) :
    HasDerivWithinAt T
      ((T a - T 0) * (↑(haunit.unit⁻¹) : A →L[ℂ] A)) (Set.Ici 0) 0 := by
  have hcancel : integratedContinuousLinearMap T a *
      (↑(haunit.unit⁻¹) : A →L[ℂ] A) = 1 := IsUnit.mul_val_inv haunit
  let f : ℝ → (A →L[ℂ] A) :=
    fun h => (integratedContinuousLinearMap T (h + a) -
      integratedContinuousLinearMap T h) * (↑(haunit.unit⁻¹) : A →L[ℂ] A)
  have h_eq : Set.EqOn T f (Set.Ici 0) := by
    intro h hh
    have hshift := integratedContinuousLinearMap_shift T hT hsemigroup (le_of_lt ha) hh
    dsimp [f]
    calc
      T h = T h * 1 := (mul_one _).symm
      _ = T h * integratedContinuousLinearMap T a *
          (↑(haunit.unit⁻¹) : A →L[ℂ] A) := by simp [mul_assoc, hcancel]
      _ = (integratedContinuousLinearMap T (h + a) -
          integratedContinuousLinearMap T h) *
          (↑(haunit.unit⁻¹) : A →L[ℂ] A) := by rw [hshift]
  have hinner : HasDerivAt
      (fun h : ℝ => integratedContinuousLinearMap T (h + a)) (T a) 0 := by
    have houter := integratedContinuousLinearMap_hasDerivAt T hT (0 + a)
    have hshift : HasDerivAt (fun h : ℝ => h + a) 1 0 := by
      simpa using (hasDerivAt_id (x := (0 : ℝ))).add_const a
    have hcomp := HasDerivAt.scomp_of_eq
      (h := fun h : ℝ => h + a) (g₁ := integratedContinuousLinearMap T)
      (x := (0 : ℝ)) (y := 0 + a) houter hshift rfl
    simpa [Function.comp_def, integratedContinuousLinearMap, one_smul, add_zero] using hcomp
  have hsub : HasDerivAt
      (fun h => integratedContinuousLinearMap T (h + a) -
        integratedContinuousLinearMap T h) (T a - T 0) 0 :=
    hinner.sub (integratedContinuousLinearMap_hasDerivAt T hT 0)
  have hf : HasDerivAt f
      ((T a - T 0) * (↑(haunit.unit⁻¹) : A →L[ℂ] A)) 0 := by
    simpa using hsub.mul_const (↑(haunit.unit⁻¹) : A →L[ℂ] A)
  apply hf.hasDerivWithinAt.congr h_eq
  rw [hzero]
  simp [f, integratedContinuousLinearMap, hcancel]

private theorem exists_integratedContinuousLinearMap_isUnit
    (T : ℝ → (A →L[ℂ] A)) (hT : Continuous T) (hzero : T 0 = 1) :
    ∃ a : ℝ, 0 < a ∧ IsUnit (integratedContinuousLinearMap T a) := by
  letI : NeBot (𝓝[>] (0 : ℝ)) := nhdsWithin_Ioi_neBot le_rfl
  have hI := integratedContinuousLinearMap_hasDerivAt T hT 0
  have hq : Tendsto
      (fun t : ℝ => t⁻¹ • integratedContinuousLinearMap T t)
      (𝓝[>] (0 : ℝ)) (𝓝 (1 : A →L[ℂ] A)) := by
    have hq' := hI.tendsto_slope_zero_right
    simpa [integratedContinuousLinearMap, hzero] using hq'
  have hu : ∀ᶠ t : ℝ in 𝓝[>] (0 : ℝ),
      IsUnit (t⁻¹ • integratedContinuousLinearMap T t) := by
    apply hq.eventually
    exact Units.isOpen.mem_nhds isUnit_one
  obtain ⟨a, haunit, ha⟩ := (hu.and self_mem_nhdsWithin).exists
  refine ⟨a, ha, ?_⟩
  have ha0 : a ≠ 0 := ne_of_gt ha
  have hscalar : IsUnit ((Units.mk0 (a : ℂ) (by exact_mod_cast ha0)) •
      (a⁻¹ • integratedContinuousLinearMap T a)) :=
    IsUnit.smul (Units.mk0 (a : ℂ) (by exact_mod_cast ha0)) haunit
  have hEq : ((Units.mk0 (a : ℂ) (by exact_mod_cast ha0)) •
      (a⁻¹ • integratedContinuousLinearMap T a)) =
      integratedContinuousLinearMap T a := by
    change (a : ℂ) • (a⁻¹ • integratedContinuousLinearMap T a) = _
    ext x
    simp [smul_apply, smul_smul, ha0]
  rwa [hEq] at hscalar

/-- A norm-continuous quantum dynamical semigroup has a bounded generator.

This is the analytic bridge from the abstract continuous semigroup API to the derivative-based
GKSL classification.  The proof uses no finite-dimensionality assumption. -/
theorem QuantumDynamicalSemigroup.exists_hasBoundedGenerator
    (Φ : QuantumDynamicalSemigroup A)
    (hΦ : QuantumDynamicalSemigroup.IsNormContinuous Φ) :
    Nonempty (QuantumDynamicalSemigroup.HasBoundedGenerator Φ) := by
  let T : ℝ → (A →L[ℂ] A) := fun t =>
    Φ.continuousLinearMap (BoundedQuantumDynamicalSemigroup.nonnegativeTime t)
  have htime : Continuous
      (BoundedQuantumDynamicalSemigroup.nonnegativeTime : ℝ → ℝ≥0) := by
    change Continuous (fun s : ℝ =>
      (⟨max s 0, le_max_right _ _⟩ : ℝ≥0))
    exact (continuous_id.max continuous_const).subtype_mk fun _ => le_max_right _ _
  have hT : Continuous T := by
    exact hΦ.comp htime
  have hzero : T 0 = 1 := by
    dsimp [T]
    have hnt : BoundedQuantumDynamicalSemigroup.nonnegativeTime 0 = 0 := by
      apply Subtype.ext
      simp [BoundedQuantumDynamicalSemigroup.nonnegativeTime]
    rw [hnt, Φ.continuousLinearMap_zero]
  have hsemigroup : ∀ {s t : ℝ}, 0 ≤ s → 0 ≤ t →
      T (s + t) = T s * T t := by
    intro s t hs ht
    have hs' := BoundedQuantumDynamicalSemigroup.nonnegativeTime_of_nonneg hs
    have ht' := BoundedQuantumDynamicalSemigroup.nonnegativeTime_of_nonneg ht
    have hst : BoundedQuantumDynamicalSemigroup.nonnegativeTime (s + t) =
        BoundedQuantumDynamicalSemigroup.nonnegativeTime s +
          BoundedQuantumDynamicalSemigroup.nonnegativeTime t := by
      apply Subtype.ext
      change max (s + t) 0 = max s 0 + max t 0
      rw [max_eq_left (add_nonneg hs ht), max_eq_left hs, max_eq_left ht]
    dsimp [T]
    rw [hst, Φ.continuousLinearMap_add]
  obtain ⟨a, ha, haunit⟩ := exists_integratedContinuousLinearMap_isUnit T hT hzero
  let G : A →L[ℂ] A :=
    (T a - T 0) * (↑(haunit.unit⁻¹) : A →L[ℂ] A)
  have hG := hasDerivWithinAt_of_integratedContinuousLinearMap_isUnit
    T hT hzero hsemigroup ha haunit
  refine ⟨{ generator := G, has_deriv := ?_ }⟩
  intro b
  let ev : (A →L[ℂ] A) →L[ℝ] A :=
    (ContinuousLinearMap.apply ℂ A b).restrictScalars ℝ
  have hev : HasDerivWithinAt (fun _ : ℝ => ev) 0 (Set.Ici 0) 0 :=
    (hasDerivAt_const (x := (0 : ℝ)) (c := ev)).hasDerivWithinAt
  have hb := hev.clm_apply hG
  have hb' : HasDerivWithinAt (fun y : ℝ => ev (T y)) (ev G) (Set.Ici 0) 0 := by
    simpa using hb
  simpa [T, ev, QuantumDynamicalSemigroup.continuousLinearMap_apply] using hb'

/-! The same integrated-semigroup argument, exposed over an arbitrary complete normed real
algebra, so matrix transfer representations and bounded-operator representations share the proof. -/
namespace NormedAlgebraSemigroup

variable {E : Type*} [NormedRing E] [NormedAlgebra ℝ E] [CompleteSpace E]

noncomputable def integrated (T : ℝ → E) (t : ℝ) : E :=
  ∫ x in (0 : ℝ)..t, T x

lemma integrated_continuous (T : ℝ → E) (hT : Continuous T) :
    Continuous (integrated T) := by
  exact (differentiable_integral_of_continuous hT).continuous

private lemma integrated_hasDerivAt (T : ℝ → E) (hT : Continuous T) (t : ℝ) :
    HasDerivAt (integrated T) (T t) t := by
  exact intervalIntegral.integral_hasDerivAt_right
    (hT.intervalIntegrable _ _) (hT.stronglyMeasurableAtFilter volume (𝓝 t))
      hT.continuousAt

private lemma integrated_shift (T : ℝ → E) (hT : Continuous T)
    (hsemigroup : ∀ {s t : ℝ}, 0 ≤ s → 0 ≤ t → T (s + t) = T s * T t)
    {a h : ℝ} (ha : 0 ≤ a) (hh : 0 ≤ h) :
    integrated T (h + a) - integrated T h = T h * integrated T a := by
  rw [show integrated T (h + a) - integrated T h = ∫ x in h..h+a, T x by
    have hsplit := intervalIntegral.integral_add_adjacent_intervals
      (f := T) (μ := volume) (a := (0 : ℝ)) (b := h) (c := h + a)
      (hT.intervalIntegrable (μ := volume) _ _) (hT.intervalIntegrable (μ := volume) _ _)
    change (∫ x in 0..h + a, T x) - ∫ x in 0..h, T x = _
    rw [← hsplit]
    abel]
  have hshift := intervalIntegral.integral_comp_add_right
    (f := T) (a := (0 : ℝ)) (b := a) h
  calc
    (∫ x in h..h+a, T x) = ∫ x in 0..a, T (x + h) := by
      rw [hshift]
      simp [add_comm]
    _ = ∫ x in 0..a, T h * T x := by
      apply intervalIntegral.integral_congr
      intro x hx
      change T (x + h) = T h * T x
      have hx' : x ∈ Set.Icc (0 : ℝ) a := by
        rcases Set.mem_uIcc.mp hx with hx' | hx'
        · exact hx'
        · constructor <;> linarith [hx'.1, hx'.2]
      simpa [add_comm] using hsemigroup hh hx'.1
    _ = T h * integrated T a := by
      rw [integrated]
      change (∫ x in 0..a, (ContinuousLinearMap.mul ℝ E (T h)) (T x)) = _
      rw [ContinuousLinearMap.intervalIntegral_comp_comm
        (ContinuousLinearMap.mul ℝ E (T h))
        (hT.intervalIntegrable (μ := volume) (0 : ℝ) a)]
      rfl

theorem hasDerivWithinAt_of_integrated_isUnit
    (T : ℝ → E) (hT : Continuous T) (hzero : T 0 = 1)
    (hsemigroup : ∀ {s t : ℝ}, 0 ≤ s → 0 ≤ t → T (s + t) = T s * T t)
    {a : ℝ} (ha : 0 < a) (haunit : IsUnit (integrated T a)) :
    HasDerivWithinAt T
      ((T a - T 0) * (↑(haunit.unit⁻¹) : E)) (Set.Ici 0) 0 := by
  have hcancel : integrated T a * (↑(haunit.unit⁻¹) : E) = 1 :=
    IsUnit.mul_val_inv haunit
  let f : ℝ → E := fun h =>
    (integrated T (h + a) - integrated T h) * (↑(haunit.unit⁻¹) : E)
  have h_eq : Set.EqOn T f (Set.Ici 0) := by
    intro h hh
    have hshift := integrated_shift T hT hsemigroup (le_of_lt ha) hh
    dsimp [f]
    calc
      T h = T h * 1 := (mul_one _).symm
      _ = T h * integrated T a * (↑(haunit.unit⁻¹) : E) := by
        simp [mul_assoc, hcancel]
      _ = (integrated T (h + a) - integrated T h) *
          (↑(haunit.unit⁻¹) : E) := by rw [hshift]
  have hinner : HasDerivAt (fun h : ℝ => integrated T (h + a)) (T a) 0 := by
    have houter := integrated_hasDerivAt T hT (0 + a)
    have hshift : HasDerivAt (fun h : ℝ => h + a) 1 0 := by
      simpa using (hasDerivAt_id (x := (0 : ℝ))).add_const a
    have hcomp := HasDerivAt.scomp_of_eq
      (h := fun h : ℝ => h + a) (g₁ := integrated T)
      (x := (0 : ℝ)) (y := 0 + a) houter hshift rfl
    simpa [Function.comp_def, integrated, one_smul, add_zero] using hcomp
  have hsub : HasDerivAt
      (fun h : ℝ => integrated T (h + a) - integrated T h) (T a - T 0) 0 :=
    hinner.sub (integrated_hasDerivAt T hT 0)
  have hf : HasDerivAt f
      ((T a - T 0) * (↑(haunit.unit⁻¹) : E)) 0 := by
    simpa using hsub.mul_const (↑(haunit.unit⁻¹) : E)
  apply hf.hasDerivWithinAt.congr h_eq
  rw [hzero]
  simp [f, integrated, hcancel]

theorem exists_integrated_isUnit (T : ℝ → E) (hT : Continuous T) (hzero : T 0 = 1) :
    ∃ a : ℝ, 0 < a ∧ IsUnit (integrated T a) := by
  letI : NeBot (𝓝[>] (0 : ℝ)) := nhdsWithin_Ioi_neBot le_rfl
  have hI := integrated_hasDerivAt T hT 0
  have hq : Tendsto (fun t : ℝ => t⁻¹ • integrated T t)
      (𝓝[>] (0 : ℝ)) (𝓝 (1 : E)) := by
    have hq' := hI.tendsto_slope_zero_right
    simpa [integrated, hzero] using hq'
  have hu : ∀ᶠ t : ℝ in 𝓝[>] (0 : ℝ),
      IsUnit (t⁻¹ • integrated T t) := by
    apply hq.eventually
    exact Units.isOpen.mem_nhds isUnit_one
  obtain ⟨a, haunit, ha⟩ := (hu.and self_mem_nhdsWithin).exists
  refine ⟨a, ha, ?_⟩
  have ha0 : a ≠ 0 := ne_of_gt ha
  have hscalar : IsUnit ((Units.mk0 a ha0) • (a⁻¹ • integrated T a)) :=
    IsUnit.smul (Units.mk0 a ha0) haunit
  have hEq : ((Units.mk0 a ha0) • (a⁻¹ • integrated T a)) = integrated T a := by
    change a • (a⁻¹ • integrated T a) = _
    simp [smul_smul, ha0]
  rwa [hEq] at hscalar

end NormedAlgebraSemigroup

/-- Choose the bounded generator supplied by norm continuity. -/
noncomputable def QuantumDynamicalSemigroup.toHasBoundedGenerator
    (Φ : QuantumDynamicalSemigroup A)
    (hΦ : QuantumDynamicalSemigroup.IsNormContinuous Φ) :
    QuantumDynamicalSemigroup.HasBoundedGenerator Φ :=
  Classical.choice (Φ.exists_hasBoundedGenerator hΦ)

/-- Package a norm-continuous quantum dynamical semigroup as an exponential semigroup. -/
noncomputable def QuantumDynamicalSemigroup.toBoundedQuantumDynamicalSemigroup
    (Φ : QuantumDynamicalSemigroup A)
    (hΦ : QuantumDynamicalSemigroup.IsNormContinuous Φ) :
    BoundedQuantumDynamicalSemigroup A :=
  (Φ.toHasBoundedGenerator hΦ).toBoundedQuantumDynamicalSemigroup

@[simp]
lemma QuantumDynamicalSemigroup.toHasBoundedGenerator_generator
    (Φ : QuantumDynamicalSemigroup A)
    (hΦ : QuantumDynamicalSemigroup.IsNormContinuous Φ) :
    (Φ.toHasBoundedGenerator hΦ).generator =
      (Φ.toBoundedQuantumDynamicalSemigroup hΦ).generator := by
  rfl

end NormContinuousGenerator

end OperatorAlgebra
