/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Physlib.QuantumMechanics.Qubit.Dynamics

/-!

# Stone's theorem for SO(3): every observable generates a one-parameter rotation group

Every observable `Hobs` produces, via `Qubit.unitaryEvolution`, a one-parameter *unitary* group
(Stone's theorem in its usual Hilbert-space form, here borrowed abstractly from
`selfAdjoint.expUnitary`). Composing with `Qubit.R` pushes this down to a one-parameter group of
*rotations* of the Bloch ball, `Qubit.rotationFlow`. Its generator — the qubit's `so(3)`, the
Lie algebra of `SO(3)` — is the **adjoint action** of the observable, `Qubit.adjointAction Hobs :
v ↦ 2 • (h ⨯₃ v)`, where `h` is `Hobs`'s traceless part: this is exactly what
`Qubit.hasDerivAt_blochTrajectory` already computed, just isolated here as its own linear map
rather than left inside a derivative statement.

`adjointAction Hobs` needs no separate construction or proof: `crossProduct` is already Mathlib's
`(Fin 3 → ℝ) →ₗ[ℝ] (Fin 3 → ℝ) →ₗ[ℝ] Fin 3 → ℝ`, so partially applying it and scaling by `2` is a
`LinearMap` for free.

This is also the `so(3)`-level shadow of the Lie-algebra adjoint representation that
`Physlib.Mathematics.OperatorAlgebra.JordanLie`'s `LieRing (Observable A)`/`LieAlgebra ℝ
(Observable A)` instances now make available in the abstract (`b ↦ ⁅Hobs, b⁆ₒ`, Mathlib's usual
`ad`) — the precise relationship between the two (`observableEquiv`-conjugate) is not yet checked,
left as a `TODO`.

-/

@[expose] public section

open scoped ComplexOrder CStarAlgebra Matrix
open Module OperatorAlgebra

namespace Qubit

variable {A : Type*} [OperatorAlgebra A] [QubitAlgebra A]

/-- The adjoint action of an observable on Bloch vectors: `adjointAction Hobs v = 2 • (h ⨯₃ v)`,
where `h` is `Hobs`'s traceless part (`Qubit.observableEquiv`). This is the generator, in `so(3)`,
of the one-parameter rotation group `Qubit.rotationFlow Hobs` below. No proof obligation: `2 •` a
partially-applied `crossProduct` is already linear. -/
noncomputable def adjointAction (Hobs : Observable A) : (Fin 3 → ℝ) →ₗ[ℝ] (Fin 3 → ℝ) :=
  (2 : ℝ) • crossProduct (observableEquiv Hobs).2

lemma adjointAction_apply (Hobs : Observable A) (v : Fin 3 → ℝ) :
    adjointAction Hobs v = (2 : ℝ) • ((observableEquiv Hobs).2 ⨯₃ v) :=
  rfl

/-- The one-parameter group of rotations generated by an observable's Hamiltonian flow: `Qubit.R`
of the unitary evolution `Qubit.unitaryEvolution`. Tagged `sorryful`: it is built from `Qubit.R`,
itself not yet constructed. -/
@[sorryful]
noncomputable def rotationFlow (Hobs : Observable A) (t : ℝ) : (Fin 3 → ℝ) →ₗ[ℝ] (Fin 3 → ℝ) :=
  R (unitaryEvolution Hobs t)

/-- Every member of the flow is a genuine rotation — free from `Qubit.isRotation_R`, itself
tagged `sorryful`. -/
@[sorryful]
lemma isRotation_rotationFlow (Hobs : Observable A) (t : ℝ) :
    IsRotation (rotationFlow Hobs t) :=
  isRotation_R (unitaryEvolution Hobs t)

/-- At time `0`, the rotation flow is the identity. -/
@[sorryful]
lemma rotationFlow_zero (Hobs : Observable A) : rotationFlow Hobs 0 = LinearMap.id :=
  sorry

TODO "Prove `Qubit.rotationFlow_zero` from `Qubit.unitaryEvolution_zero` and `Qubit.R_one`."

/-- The group law: evolving by `s + t` is evolving by `s` then by `t`. -/
@[sorryful]
lemma rotationFlow_add (Hobs : Observable A) (s t : ℝ) :
    rotationFlow Hobs (s + t) = (rotationFlow Hobs t).comp (rotationFlow Hobs s) :=
  sorry

TODO "Prove `Qubit.rotationFlow_add` from `Qubit.unitaryEvolution_add` and `Qubit.R_comp` (check
  the composition order against `Qubit.R_comp`'s own — `unitaryEvolution` commutes with itself,
  so `unitaryEvolution Hobs s * unitaryEvolution Hobs t = unitaryEvolution Hobs t *
  unitaryEvolution Hobs s`, but state it in whichever order falls out directly to avoid an
  unnecessary extra rewrite)."

/-- **Stone's theorem for `SO(3)`**: the one-parameter rotation group generated by an observable
has, at every time (not just `t = 0`), derivative equal to `Qubit.adjointAction Hobs` evaluated at
the current point — restating `Qubit.hasDerivAt_blochTrajectory` with the generator isolated as
its own linear map instead of a bare expression. -/
@[sorryful]
lemma hasDerivAt_rotationFlow_apply (Hobs : Observable A) (v : Fin 3 → ℝ) (t : ℝ) :
    HasDerivAt (fun t => rotationFlow Hobs t v) (adjointAction Hobs (rotationFlow Hobs t v)) t :=
  sorry

TODO "`Qubit.hasDerivAt_rotationFlow_apply` should be definitionally
  `Qubit.hasDerivAt_blochTrajectory Hobs v t` once `Qubit.blochTrajectory Hobs v = fun t =>
  rotationFlow Hobs t v` and `Qubit.adjointAction_apply` are unfolded — no new mathematics, just
  repackaging the existing derivative statement around the newly-named generator."

end Qubit
