/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Physlib.QuantumMechanics.OperatorAlgebra.Hamiltonian
public import Physlib.QuantumMechanics.OperatorAlgebra.Matrix
public import Physlib.Mathematics.OneParameterSubgroups.Unitary
public import Physlib.Relativity.PauliMatrices.SelfAdjoint

/-!

# Qubit observables and their time evolution

Every qubit observable admits a unique Pauli decomposition
`A = a₀ I + a₁ σ₁ + a₂ σ₂ + a₃ σ₃`, so the real vector space of qubit observables `𝒪[Fin 2]` is
canonically identified with its four real Pauli coefficients via `observablePauliEquiv`.

Given a scalar `a₀` and a Pauli vector `a`, `observableOfComponents a₀ a` builds the
corresponding observable directly. Its physical time evolution `Observable.timeEvolutionℏ`
(already generic, from `QuantumMechanics.OperatorAlgebra.Hamiltonian`) then has the familiar
closed form: a global phase from `a₀`, times a cosine-sine rotation about `a`.

The whole proof rests on two facts, each doing exactly one job:

* `vectorObservable_sq`, the Pauli product formula `(a · σ)² = ‖a‖² • 1`, transported in one step
  from `PauliMatrix.vectorMatrix_sq` along `operatorAlgebraEquivMatrix`;
* `ContinuousLinearMap.exp_neg_I_smul_of_sq_eq_smul_one`, the generic fact (from
  `Mathematics.OneParameterSubgroups.Unitary`) that an operator squaring to a real multiple of
  the identity has an easy exponential.

## Main results

* `observablePauliEquiv`: qubit observables are equivalent to their four real Pauli coefficients.
* `observableOfComponents`: the observable with given scalar and Pauli-vector components.
* `timeEvolutionℏ_apply_observableOfComponents`: its physical time evolution, in closed form.

-/

@[expose] public section

noncomputable section

namespace QuantumMechanics

namespace Qubit

open Constants Matrix

/-- Qubit observables are equivalent to their four real Pauli coefficients. -/
noncomputable def observablePauliEquiv :
    𝒪[Fin 2] ≃ₗ[ℝ] ((Fin 1 ⊕ Fin 3) →₀ ℝ) :=
  observableMatrixEquiv.trans (Module.Basis.repr PauliMatrix.pauliBasis)


/-!
## The observable of a Pauli vector
-/

/-- `a · σ` is self-adjoint for any real Pauli vector `a`. -/
lemma vectorMatrix_isSelfAdjoint (a : Fin 3 → ℝ) :
    (PauliMatrix.vectorMatrix a)ᴴ = PauliMatrix.vectorMatrix a := by
  simp only [PauliMatrix.vectorMatrix, conjTranspose_sum, conjTranspose_smul]
  apply Finset.sum_congr rfl
  intro i _
  rw [PauliMatrix.pauliMatrix_selfAdjoint]
  simp

/-- The observable `a · σ` for a real Pauli vector `a`. -/
noncomputable def vectorObservable (a : EuclideanSpace ℝ (Fin 3)) :
    𝒪[Fin 2] :=
  observableMatrixEquiv.symm
    ⟨PauliMatrix.vectorMatrix (a : Fin 3 → ℝ), vectorMatrix_isSelfAdjoint (a : Fin 3 → ℝ)⟩

@[simp]
lemma operatorAlgebraEquivMatrix_vectorObservable (a : EuclideanSpace ℝ (Fin 3)) :
    operatorAlgebraEquivMatrix (vectorObservable a : 𝒜[Fin 2]) =
      PauliMatrix.vectorMatrix (a : Fin 3 → ℝ) :=
  operatorAlgebraEquivMatrix.apply_symm_apply _

/-- The Pauli product formula, at the operator level: `a · σ` squares to `‖a‖² • 1`. -/
lemma vectorObservable_sq (a : EuclideanSpace ℝ (Fin 3)) :
    (vectorObservable a : 𝒜[Fin 2]) * (vectorObservable a : 𝒜[Fin 2]) =
      ((‖a‖ ^ 2 : ℝ) : ℂ) • (1 : 𝒜[Fin 2]) := by
  apply operatorAlgebraEquivMatrix.injective
  show operatorAlgebraEquivMatrix
      ((vectorObservable a : 𝒜[Fin 2]) * (vectorObservable a : 𝒜[Fin 2])) =
    operatorAlgebraEquivMatrix (((‖a‖ ^ 2 : ℝ) : ℂ) • (1 : 𝒜[Fin 2]))
  rw [map_mul operatorAlgebraEquivMatrix, map_smul (M := ℂ) operatorAlgebraEquivMatrix, map_one,
    operatorAlgebraEquivMatrix_vectorObservable, PauliMatrix.vectorMatrix_sq]
  congr 1
  rw [EuclideanSpace.norm_eq, Real.sq_sqrt (by positivity)]
  simp only [Real.norm_eq_abs, sq_abs]
  norm_cast


/-!
## An observable given by four real numbers
-/

/-- The qubit observable with scalar part `a₀` and Pauli-vector part `a`. -/
noncomputable def observableOfComponents (a₀ : ℝ) (a : EuclideanSpace ℝ (Fin 3)) :
    𝒪[Fin 2] :=
  a₀ • 1 + vectorObservable a

lemma coe_observableOfComponents (a₀ : ℝ) (a : EuclideanSpace ℝ (Fin 3)) :
    (observableOfComponents a₀ a : 𝒜[Fin 2]) =
      a₀ • (1 : 𝒜[Fin 2]) + (vectorObservable a : 𝒜[Fin 2]) := by
  simp [observableOfComponents]

/-- The unitary group generated by the observable with components `(a₀, a)`, evaluated as the
familiar phase-times-rotation formula: a global phase from the scalar part, times a cosine-sine
rotation about the Pauli vector `a`. -/
theorem timeEvolutionℏ_apply_observableOfComponents (a₀ : ℝ) (a : EuclideanSpace ℝ (Fin 3))
    (t : ℝ) :
    (Observable.timeEvolutionℏ (observableOfComponents a₀ a) t : 𝒜[Fin 2]) =
      Complex.exp (-(t : ℂ) * Complex.I * a₀ / ℏ) •
        ((Real.cos (t * ‖a‖ / ℏ) : ℂ) • (1 : 𝒜[Fin 2]) -
          ((Real.sin (t * ‖a‖ / ℏ) : ℂ) * Complex.I / ‖a‖) •
            (vectorObservable a : 𝒜[Fin 2])) := by
  rw [Observable.timeEvolutionℏ_apply, coe_observableOfComponents,
    smul_add (-(t : ℂ) * Complex.I / ℏ) (a₀ • (1 : 𝒜[Fin 2])) (vectorObservable a : 𝒜[Fin 2])]
  rw [show (-(t : ℂ) * Complex.I / ℏ) • (a₀ • (1 : 𝒜[Fin 2])) =
      (-(t : ℂ) * Complex.I * a₀ / ℏ) • (1 : 𝒜[Fin 2]) by
    rw [show a₀ • (1 : 𝒜[Fin 2]) = (a₀ : ℂ) • (1 : 𝒜[Fin 2]) from
      (Complex.coe_smul a₀ (1 : 𝒜[Fin 2])).symm, smul_smul]
    congr 1
    ring]
  rw [show (-(t : ℂ) * Complex.I / ℏ) • (vectorObservable a : 𝒜[Fin 2]) =
      (-((t / ℏ : ℝ) : ℂ) * Complex.I) • (vectorObservable a : 𝒜[Fin 2]) by
    congr 1
    push_cast
    ring]
  let _ : NormedAlgebra ℚ (𝒜[Fin 2]) := .restrictScalars ℚ ℂ _
  have hcomm : Commute ((-(t : ℂ) * Complex.I * a₀ / ℏ) • (1 : 𝒜[Fin 2]))
      ((-((t / ℏ : ℝ) : ℂ) * Complex.I) • (vectorObservable a : 𝒜[Fin 2])) :=
    (Commute.one_left _).smul_left _
  rw [NormedSpace.exp_add_of_commute hcomm, ContinuousLinearMap.exp_smul_one,
    ContinuousLinearMap.exp_neg_I_smul_of_sq_eq_smul_one (vectorObservable a).property ‖a‖
      (vectorObservable_sq a) (t / ℏ)]
  rw [show ‖a‖ * (t / ℏ) = t * ‖a‖ / ℏ by ring, smul_mul_assoc, one_mul]

end Qubit

end QuantumMechanics
