/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Algebra.Quaternion
public import Mathlib.Data.Complex.Basic
public import Mathlib.LinearAlgebra.StdBasis

/-!

# The Pauli relations, as a concrete presented algebra

`Qubit.QubitAlgebra` (`Basic.lean`) takes `gen_sq`, `gen_mul_cyc`, and `pauliBasis` as hypotheses
on an arbitrary `A`. This file answers the natural follow-up question: is there actually a
unital `ℂ`-algebra satisfying `gen_sq`/`gen_mul_cyc` in which `1, gen 0, gen 1, gen 2` is a basis,
*proved*, not assumed? Yes — this file constructs one, `Qubit.Presentation.PauliAlgebra`, and
proves it.

## Construction, and why no matrix is chosen

The generators-and-relations idea is: take the free unital associative `ℂ`-algebra on three
letters `X, Y, Z` and quotient by the two-sided ideal generated by the Pauli relations. Any word
in the generators can be *rewritten* down to a scalar multiple of `1, X, Y,` or `Z` using only
`gen_sq` (no letter ever needs repeating) and `gen_mul_cyc` (any two adjacent, distinct letters
collapse to a scalar times the third) — this is the easy half, spanning, and needs no relation
beyond termination of that rewrite.

The hard half is that no *further* collapse happens — that the rewrite system is confluent, so
that reducing a word two different ways always agrees. Formalizing that confluence check
literally on the free algebra (`Mathlib.Algebra.FreeAlgebra`) is one way to get it; this file
takes a shortcut to the same fact by recognizing the relations directly as (a relabelling of) an
algebra Mathlib has already built and already proved associative: `Mathlib.Algebra.Quaternion`'s
`QuaternionAlgebra ℂ (-1) 0 (-1)`, Hamilton's quaternions with complex coefficients. Writing
`i, j, k` for its standard generators (`i² = j² = k² = -1`, `ij = k = -ji`, cyclically),
`gen 0 := I • i, gen 1 := I • j, gen 2 := I • k` satisfies exactly `gen_sq`/`gen_mul_cyc` — the
scalar `I` converts `i² = -1` into `gen 0 ^ 2 = 1` and `ij = k` into `gen 0 * gen 1 = I • gen 2`.
Associativity, distributivity, and the rest of the ring axioms transfer for free from Mathlib's
`QuaternionAlgebra` instance; the only work below is this relabelling and reading off a basis.

This is *not* a matrix representation, and is not in tension with the `SO(3)`/`{±1}`-kernel
correction elsewhere in this development, `Qubit/Unitary.lean`: the concern there was that
*definitions* stated for a general `QubitAlgebra A` must not secretly depend on a chosen
representation of `A`. Here there is no general `A` in sight — `PauliAlgebra` is one fixed,
concrete algebra, and any witness that its multiplication is consistent (whether a rewriting
confluence argument or, as here, an already-associative relabelling) is fair game.

## Scope

`PauliAlgebra` is a witness that `QubitAlgebra`'s hypotheses are jointly satisfiable, and a
natural, small such witness — not a replacement for `pauliBasis` as a hypothesis on a general
`A` (an arbitrary `QubitAlgebra A` can still be a strictly larger algebra than this one; see
`Basic.lean`'s module docstring). Turning `PauliAlgebra` into an actual `QubitAlgebra` *instance*
additionally needs a C⋆-norm and compatible order (`OperatorAlgebra`, `Basic.lean`) — by the
uniqueness of C⋆-norms, that norm is forced to be (the transport of) the operator norm on
`Matrix (Fin 2) (Fin 2) ℂ` under the algebra isomorphism `PauliAlgebra ≃ₐ[ℂ] Matrix (Fin 2)
(Fin 2) ℂ` (Artin–Wedderburn: complexified Hamilton quaternions are the full `2 × 2` matrix
algebra). That is exactly the later, genuinely matrix-needing step this development already
planned as `Qubit/Matrix.lean`; it is not done here.

-/

@[expose] public section

open Module

namespace Qubit

namespace Presentation

/-- The concrete algebra presented by the Pauli relations: Hamilton's quaternions with complex
coefficients, `i² = j² = k² = -1`, `ij = k = -ji`, cyclically. See the module docstring for why
`gen`, defined below, satisfies the Pauli relations in this algebra. -/
abbrev PauliAlgebra := QuaternionAlgebra ℂ (-1) 0 (-1)

/-- The three Pauli generators inside `PauliAlgebra`: `I` times the three quaternion units. -/
def gen : Fin 3 → PauliAlgebra :=
  ![⟨0, Complex.I, 0, 0⟩, ⟨0, 0, Complex.I, 0⟩, ⟨0, 0, 0, Complex.I⟩]

@[simp] theorem gen_zero : gen 0 = (⟨0, Complex.I, 0, 0⟩ : PauliAlgebra) := rfl
@[simp] theorem gen_one : gen 1 = (⟨0, 0, Complex.I, 0⟩ : PauliAlgebra) := rfl
@[simp] theorem gen_two : gen 2 = (⟨0, 0, 0, Complex.I⟩ : PauliAlgebra) := rfl

/-- Each generator squares to `1`. -/
theorem gen_sq (i : Fin 3) : gen i * gen i = 1 := by
  fin_cases i <;>
    · ext <;> simp [QuaternionAlgebra.mk_mul_mk, Complex.I_mul_I]

/-- The cyclic Pauli relation: `gen i * gen (i + 1) = I • gen (i + 2)`. -/
theorem gen_mul_cyc (i : Fin 3) : gen i * gen (i + 1) = Complex.I • gen (i + 2) := by
  fin_cases i <;>
    · ext <;> simp [QuaternionAlgebra.mk_mul_mk, QuaternionAlgebra.smul_mk, Complex.I_mul_I]

/-- The reversed cyclic relation: `gen (i + 1) * gen i = -I • gen (i + 2)`. -/
theorem gen_mul_cyc_symm (i : Fin 3) : gen (i + 1) * gen i = -Complex.I • gen (i + 2) := by
  fin_cases i <;>
    · ext <;> simp [QuaternionAlgebra.mk_mul_mk, QuaternionAlgebra.smul_mk, Complex.I_mul_I]

/-- The linear equivalence exhibiting `1, gen 0, gen 1, gen 2` as coordinates on `PauliAlgebra`:
forward, `c ↦ c 0 • 1 + c 1 • gen 0 + c 2 • gen 1 + c 3 • gen 2`; backward, reading off the four
components (dividing the imaginary parts by `I`, i.e. multiplying by `-I`). -/
def coordEquiv : (Fin 4 → ℂ) ≃ₗ[ℂ] PauliAlgebra :=
  LinearEquiv.ofLinearMap
    { toFun := fun c => (⟨c 0, Complex.I * c 1, Complex.I * c 2, Complex.I * c 3⟩ : PauliAlgebra)
      map_add' := by intro c c'; ext <;> simp <;> ring
      map_smul' := by intro r c; ext <;> simp <;> ring }
    { toFun := fun q => ![q.re, -Complex.I * q.imI, -Complex.I * q.imJ, -Complex.I * q.imK]
      map_add' := by intro q q'; ext i; fin_cases i <;> simp <;> ring
      map_smul' := by intro r q; ext i; fin_cases i <;> simp <;> ring }
    (by ext q <;> simp <;> ring_nf <;> simp [Complex.I_sq])
    (by ext c i; fin_cases i <;> simp <;> ring_nf <;> simp [Complex.I_sq])

/-- `1, gen 0, gen 1, gen 2` form a complex basis of `PauliAlgebra` — a genuine theorem, not a
hypothesis: `PauliAlgebra` is (by construction) coordinatized by `Fin 4 → ℂ` via `coordEquiv`,
whose standard basis transports to exactly `Fin.cons 1 gen`. -/
noncomputable def pauliBasis : Basis (Fin 4) ℂ PauliAlgebra :=
  (Pi.basisFun ℂ (Fin 4)).map coordEquiv

/-- The basis `pauliBasis` is exactly `1` followed by the generators. -/
theorem pauliBasis_eq : ⇑pauliBasis = Fin.cons (1 : PauliAlgebra) gen := by
  funext i
  fin_cases i <;> simp [pauliBasis, coordEquiv, Pi.basisFun_apply] <;> rfl

end Presentation

end Qubit
