/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Physlib.QuantumMechanics.Qubit.Observable
public import Physlib.Mathematics.OperatorAlgebra.Unitary
public import Mathlib.Analysis.InnerProductSpace.PiL2

/-!

# Unitary conjugation acts on the Bloch ball by rotations

A unitary `U` acts on observables by `a ↦ U a U⋆` (`OperatorAlgebra.Unitary.automorphism`).
Conjugation fixes `1` and, since it is a ⋆-algebra automorphism, preserves self-adjointness — so
it carries the Pauli-vector sector `{σ v}` to itself, inducing a real-linear map `R U` on Bloch
vectors characterized by `U σ(v) U⋆ = σ(R U v)`.

`R U` is an isometry of `Fin 3 → ℝ` (norm-preserving), and `U ↦ R U` is compatible with
multiplication: `R (U * V) = (R U).comp (R V)`, matching how `Unitary.automorphism (U * V) =
Unitary.automorphism U ∘ Unitary.automorphism V` (verified from `Unitary.conjStarAlgAut`'s
`map_mul'`). This realizes the adjoint action `SU(2) → SO(3)`, though landing `R U` inside
`Matrix.specialOrthogonalGroup (Fin 3) ℝ` (fixing a basis, checking the determinant) and
identifying the kernel with the scalar unitaries (the double cover, kernel `{±1}`) are left for
later — see `Qubit/todo.md`.

-/

@[expose] public section

open scoped ComplexOrder CStarAlgebra
open Module OperatorAlgebra

namespace Qubit

variable {A : Type*} [OperatorAlgebra A] [QubitAlgebra A]

/-- The real-linear map on Bloch vectors induced by unitary conjugation, characterized by
`Qubit.coe_R`: `U σ(v) U⋆ = σ(R U v)`. -/
@[sorryful]
noncomputable def R (U : Unitary A) : (Fin 3 → ℝ) →ₗ[ℝ] (Fin 3 → ℝ) :=
  sorry

TODO "Construct `Qubit.R`, now that `Qubit.observableEquiv` exists. `Unitary.automorphism U (σ v)`
  is self-adjoint (`Qubit.isSelfAdjoint_σ`, ⋆-algebra automorphisms preserve `IsSelfAdjoint`), so
  `observableEquiv ⟨automorphism U (σ v), _⟩ : ℝ × (Fin 3 → ℝ)` always makes sense; the real
  content is showing its *first* (scalar) component is `0`, so only the second component is
  needed for `R U v`. Concretely: `Qubit.trace (U a U⋆) = Qubit.trace a` for every `a`, hence
  `σ v`'s (already-zero, since `σ v` is a pure Pauli vector) trace is preserved. The conjugation
  invariance itself reduces to *cyclicity* of `trace`, `trace (x y) = trace (y x)` for all
  `x y : A` (then `trace (U a U⋆) = trace ((U a) U⋆) = trace (U⋆ (U a)) = trace ((U⋆ U) a) =
  trace a` using `U⋆ U = 1`) — and cyclicity itself is checkable abstractly, no matrices: `trace`
  is `ℂ`-bilinear in a product `trace (x y)`, so it suffices to check `trace (pauliBasis j *
  pauliBasis k) = trace (pauliBasis k * pauliBasis j)` on the 16 pairs of basis elements, which
  collapses to two trivial families (`j = 0` or `k = 0`: multiplying by `1` doesn't change the
  product; `j = k`: same term) plus the six `i ≠ j` generator pairs, each of which has *both*
  sides trace `0` (`gen i * gen j = ± i • gen k` for the third index `k`, and every generator is
  traceless, `coeff (gen k) 0 = 0` since `gen k = pauliBasis k.succ ≠ pauliBasis 0`). Once `R U v`
  is defined as `(observableEquiv ⟨automorphism U (σ v), _⟩).2`, linearity in `v` follows from
  linearity of `σ`, `automorphism U`, and `observableEquiv`. (A first attempt at formalizing this
  exact argument got tangled in `Finset.sum`/`Basis.repr` bookkeeping for the bilinear-extension
  step; the mathematical content above is checked and correct, just not yet pushed through Lean.)"

/-- The defining property of `Qubit.R`: `U σ(v) U⋆ = σ(R U v)`. -/
@[sorryful]
theorem coe_R (U : Unitary A) (v : Fin 3 → ℝ) :
    (U : A) * σ v * star (U : A) = σ (R U v) :=
  sorry

TODO "Prove `Qubit.coe_R` directly from the construction of `Qubit.R` (it should essentially be
  definitional once `R` is built from `Unitary.automorphism`/`Unitary.observable` via
  `Qubit.observableEquiv`, using `OperatorAlgebra.Unitary.automorphism_apply`)."

/-- `R U` is an isometry of Bloch vectors. -/
@[sorryful]
theorem norm_R_apply (U : Unitary A) (v : Fin 3 → ℝ) :
    ‖(WithLp.toLp 2 (R U v) : EuclideanSpace ℝ (Fin 3))‖ =
      ‖(WithLp.toLp 2 v : EuclideanSpace ℝ (Fin 3))‖ :=
  sorry

TODO "Prove `Qubit.norm_R_apply` from `Qubit.coe_R` and `Qubit.σ_sq`: `‖v‖² • 1 = σ v * σ v = U⋆
  (U σ v U⋆)(U σ v U⋆) U = U⋆ σ(R U v) σ(R U v) U = U⋆ (‖R U v‖² • 1) U = ‖R U v‖² • 1` (using
  `U⋆ U = 1`), then cancel and take square roots."

/-- `R U` is orientation-preserving: its determinant is `1`, not just `±1`. No basis or matrix
is chosen — `LinearMap.det` is already basis-independent. Together with `Qubit.norm_R_apply`
(orthogonal), this is exactly "`R U` lies in `SO(3)`", stated abstractly. -/
@[sorryful]
theorem det_R_eq_one (U : Unitary A) :
    LinearMap.det (R U : (Fin 3 → ℝ) →ₗ[ℝ] (Fin 3 → ℝ)) = 1 :=
  sorry

TODO "Prove `Qubit.det_R_eq_one`. `Unitary A` is path-connected to `1` through unitaries close to
  `1` (or: `A` unital C⋆-algebra, `unitary A` is generated by `exp (i • selfAdjoint)`, i.e. every
  unitary is `exp(i h)` for some self-adjoint `h`), along which `U ↦ det (R U)` is continuous and
  valued in `{-1, 1}` (an isometry's determinant has absolute value `1`); a connected image of a
  discrete set is a point, and `det (R 1) = det LinearMap.id = 1` (`Qubit.R_one`) fixes which
  one. (Alternative route once `Qubit/Dynamics.lean` exists: differentiate `t ↦ det (R (U t))`
  along a one-parameter unitary group and show the derivative vanishes.)"

/-- `R U` lies in `SO(3)`, packaged as a `Prop` with no basis or matrix in sight: a real-linear
self-map of `Fin 3 → ℝ` is a rotation iff it is norm-preserving and has determinant `1`. -/
def IsRotation (f : (Fin 3 → ℝ) →ₗ[ℝ] (Fin 3 → ℝ)) : Prop :=
  (∀ v, ‖(WithLp.toLp 2 (f v) : EuclideanSpace ℝ (Fin 3))‖ =
    ‖(WithLp.toLp 2 v : EuclideanSpace ℝ (Fin 3))‖) ∧ LinearMap.det f = 1

/-- `R U` is a rotation, for every unitary `U`. Tagged `sorryful`: it just tuples
`Qubit.norm_R_apply` and `Qubit.det_R_eq_one`, both themselves not yet proved. -/
@[sorryful]
theorem isRotation_R (U : Unitary A) : IsRotation (R U) :=
  ⟨norm_R_apply U, det_R_eq_one U⟩

/-- `R` is compatible with multiplication, matching `Unitary.automorphism (U * V) =
Unitary.automorphism U ∘ Unitary.automorphism V`. -/
@[sorryful]
theorem R_comp (U V : Unitary A) : R (U * V) = (R U).comp (R V) :=
  sorry

TODO "Prove `Qubit.R_comp` from `Qubit.coe_R` applied twice and
  `OperatorAlgebra.Unitary.automorphism_apply`'s multiplicativity (`Unitary.conjStarAlgAut`'s
  `map_mul'`: `(U * V) * a * star (U * V) = U * (V * a * star V) * star U`), plus injectivity of
  `Qubit.σ` (from `QubitAlgebra.pauliBasis`) to cancel it from both sides."

/-- The identity unitary induces the identity map on Bloch vectors. -/
@[sorryful]
theorem R_one : R (A := A) 1 = LinearMap.id :=
  sorry

TODO "Prove `Qubit.R_one` from `Qubit.coe_R` at `U = 1` (`1 * σ v * star 1 = σ v`) and
  injectivity of `Qubit.σ`."

/-! ### The kernel of `R`: the `SU(2) → SO(3)` double cover, abstractly

`R`'s kernel is the *center* of `Unitary A` — the scalar unitaries `{c • 1 : ‖c‖ = 1}`, an
abstract circle `U(1)`. This is the honest statement for `Unitary A`, the *full* unitary group
(the analogue of `U(2)`, acting through its quotient `U(2)/U(1) ≅ PU(2) ≅ SO(3)`).

Restricting to the *special* (determinant-`1`) unitaries cuts this down to the familiar textbook
kernel `{±1}` — and this needs no matrices and no `Qubit/Matrix.lean`: `SO(3)` is already abstract
(`Qubit.IsRotation`/`Qubit.isRotation_R` use only `LinearMap.det`, basis-free), and a `2 × 2`
determinant on `A` itself is *equally* abstract, since it is just the Cayley–Hamilton formula
`det a = (trace a ^ 2 - trace (a * a)) / 2` in the trace `Qubit.trace` already built from
`QubitAlgebra.pauliBasis` (`Qubit/Observable.lean`) — no chosen matrix representation anywhere. -/

/-- A scalar unitary: a unimodular complex multiple of `1`. -/
def IsScalarUnitary (U : Unitary A) : Prop :=
  ∃ c : ℂ, ‖c‖ = 1 ∧ (U : A) = c • 1

/-- `R`'s kernel is exactly the scalar unitaries. -/
@[sorryful]
theorem R_eq_id_iff_isScalarUnitary (U : Unitary A) :
    R U = LinearMap.id ↔ IsScalarUnitary U :=
  sorry

TODO "Prove `Qubit.R_eq_id_iff_isScalarUnitary`.
  (⇐, easy) If `U = c • 1` with `‖c‖ = 1`: `(c • 1) * σ v * star (c • 1) = (c * star c) • σ v =
  (‖c‖ ^ 2 : ℂ) • σ v = σ v`, so `Qubit.coe_R` gives `σ (R U v) = σ v` for all `v`; conclude
  `R U v = v` by injectivity of `Qubit.σ` (from `QubitAlgebra.pauliBasis`).
  (⇒, the substantive direction) If `R U = LinearMap.id`, `Qubit.coe_R` gives `U * σ v * star U =
  σ v` for every `v`, i.e. `U` commutes with every `σ v` (multiply both sides by `star U` and use
  unitarity); together with commuting with `1`, and `QubitAlgebra.pauliBasis_eq`, `U` is central
  in `A`. Finish by showing `A`'s center is exactly the scalars `{c • 1}` — a form of Schur's
  lemma resting on `QubitAlgebra`'s relations (`gen_sq`, `gen_mul_cyc`) pinning `A` down as a
  simple, matrix-like algebra with trivial center; not yet available as a standalone fact, and the
  reason this whole iff is one `sorry` rather than two."

/-- A special unitary: a unitary of determinant `1` — the abstract, matrix-free `SU(2)`. -/
def IsSpecialUnitary (U : Unitary A) : Prop :=
  det (U : A) = 1

/-- **`SU(2) → SO(3)`, the familiar double cover**: among the *special* unitaries, `R`'s kernel is
exactly `{1, -1}`. Combines `Qubit.R_eq_id_iff_isScalarUnitary` (kernel = scalar unitaries `c • 1`)
with `Qubit.det_smul_one` (`det (c • 1) = c ^ 2`, so `IsSpecialUnitary` forces `c ^ 2 = 1`, i.e.
`c = 1 ∨ c = -1` over `ℂ`). -/
@[sorryful]
theorem R_eq_id_iff_eq_one_or_eq_neg_one_of_isSpecialUnitary
    (U : Unitary A) (hU : IsSpecialUnitary U) :
    R U = LinearMap.id ↔ (U : A) = 1 ∨ (U : A) = -1 :=
  sorry

TODO "Prove `Qubit.R_eq_id_iff_eq_one_or_eq_neg_one_of_isSpecialUnitary` from
  `Qubit.R_eq_id_iff_isScalarUnitary`: `R U = id ↔ ∃ c, ‖c‖ = 1 ∧ (U : A) = c • 1`. Given `hU :
  det (U : A) = 1`, substituting `(U : A) = c • 1` and `Qubit.det_smul_one` forces `c ^ 2 = 1`,
  hence (`sq_eq_one_iff_of_ne_neg_one`-style case split over `ℂ`, or `Complex`'s
  root-of-unity/factorization lemmas) `c = 1 ∨ c = -1`; conversely `‖(1 : ℂ)‖ = ‖(-1 : ℂ)‖ = 1` so
  both directions of the outer iff close by substitution back into
  `Qubit.R_eq_id_iff_isScalarUnitary`."

end Qubit
